### ISSUE TITLE
Wont let me in sandy 2-3 bcnm dragon fight at bastok

### ISSUE THREAD

**Issue by RoodNverse** [LegionDark/Issues#317] opened 2015-09-18 02:30 UTC
**Date & Time**: 9/17/15 10:26 
**Frequency**:
**FFXI Client Version**:
**Character Name**:Dest
**Race**:mithra
**Nation**:sandy
**Main Job**:blm
**Sub Job**:whm
**Area & Coordinates**:bastok region
**Party or Solo**:
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:
**Steps To Reproduce The Issue**:   
ALL steps were taken and worked perfect   Went to BCNM but no option to do fight. 
I went to fight with someone else who started it but I did not receive kindred crest KI

Head to the Consulate of San d'Oria in the Metalworks at (H-9) on the second floor and speak to Savae E Paleade for a cutscene.
Enter the Department of Industry adjacent to the President's Office and speak to Pius.
Walk to the Craftsmen's Eatery at (G-9) and speak to Grohm.
Head to the Palborough Mines located in North Gustaberg at (K-3).
In the Palborough Mines, make your way to third floor of the mines and enter the Waughroon Shrine.

**Comment by TeoTwawki** [comment] 2015-09-18 02:55
> Multi-boxing? (multiple clients on same connection):

This needs filled in. **Especially** for this type of issue, where a quest/mission step or variable or Keyitem may have failed to trigger. Be aware that multi boxing issues are among the easiest for us to patch up affected characters for if we know that's the cause, but cannot prevent (they happen rather randomly) and that recent DarkStar issues may be causing certain events to fail to set variables or give keyitems even when nobody was multi-boxing.

Also a somewhat known issue where if you speak with a wrong consulate NPC or visit nations in a different (but perfectly legit) order, the nation 2-3 mission gets gummed up for basically no reason. 
http://legiondark.com/forums/viewtopic.php?f=21&t=722
Hate that. At least its easy to fix you up if that happened.

**Comment by RoodNverse** [comment] 2015-09-18 21:33
Thank you for the reply and sorry about not filling that info in.
 I'm actually writing this for Dest since they didn't know how to use this. Dest does not multi box, but Dest sister who is in same house may have been on. They are unsure. Dest sis name is Karri if need her name.
I'm at a different house. Dest went in the mission with me since I was on it we did the fight and she got the Cs but no KI. I don't if that info will help any, but wanted to clear that up. Thanks.

**Comment by TeoTwawki** [comment] 2015-09-18 21:42
@RoodNverse Thanks for the info.

@LegionDark/gm sounds likely this is the multi box bug again (the sister being on at same time for even a moment would be enough to randomly trigger it even hours later without a full logout from both characters), which means we can probably add the missing KI and everything will be fine. If that doesn't fix Dest up poke me in IRC (remember to say my full name so it dings me).

**Comment by Loki79** [comment] 2015-09-19 13:34
@Roamin or @PikaFox Please address this.

**Comment by PikaFox** [comment] 2015-09-21 21:55
Hey, what times are you (they) normally on? Ive been searching for someone named "Dest" in game and i havnt seen anyone with that name in game when ive been on.

**Comment by Loki79** [comment] 2015-09-26 21:13
closing this.  if he decides he wants to respond we can address then.

**Closed by Loki79** 2015-09-26 21:13 UTC
