### ISSUE TITLE
No KI after 5-1 BCNM

### ISSUE THREAD

**Issue by Skett** [LegionDark/Issues#21] opened 2015-05-27 18:23 UTC
**Date & Time**: 27/05/15 19:18:41 GMT
**Frequency**: Twice
**FFXi Client Version**: 30150508_5
**Character Name**: Skett
**Race**: Elvaan
**Main Job**: NIN
**Sub Job**: WAR
**Area & Coordinates (Type @where to get this info.)**: X:-37 Y:-28 Z:-63 (86)
**Party or Solo**: PArty
**NPC Name**: N/A
**Monster Name**: N/A
**Steps To Reproduce The Issue**: Finish 5-1 BCNM, dont get the key item for completion.
Both other ppl in my party got the KI, so we tried again thinking maybe I HP too soon, same result.

**Comment by R3P0FFXI** [comment] 2015-05-28 01:48
Tried to look for you tonight did not see you please hit me up on IRC when you are around

**Comment by Skett** [comment] 2015-05-28 10:18
Issues of being in gmt! Will be on later

**Comment by R3P0FFXI** [comment] 2015-05-28 16:50
@delkeyitem 72
@addkeyitem 73
@completemission 0 14
@addmission 0 15

**Comment by R3P0FFXI** [comment] 2015-05-28 18:43
Teo please look at this my fix did not work may be a HALVER issue Fucking Halver

**Comment by TeoTwawki** [comment] 2015-05-28 21:23
Its not Halver, is you did totally wrong thing - you needed to look at variable, and also not skip the mission.

**Comment by Skett** [comment] 2015-05-28 21:57
Let me know when to be on if I need to be guyz

**Comment by Skett** [comment] 2015-05-28 21:58
minus the z

**Comment by TeoTwawki** [comment] 2015-05-29 01:31
Fixed Skett and verified mission behaves as intended now. Closing.

**Closed by TeoTwawki** 2015-05-29 01:31 UTC
Labels: Status: Investigation / Work in progress
