### ISSUE TITLE
event moogle

### ISSUE THREAD

**Issue by ilyzia** [LegionDark/Issues#1727] opened 2017-12-12 20:54 UTC
**Date & Time**: 
12/12/17

**FFXI Client Version (use `/ver`)**: 
30171103_1

**Server's Expected Client Version matches, yes/no? (use `!ecv`)**: 
yes?

**Character Name**: 
Lyzy

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
Thf 80 Dnc 40

**NPC or Monster or item Name**: 
Anniversary Moogle 

**Zone name**: 
Windurst Waters N

**Coordinates (use `!where`)**: 
X: -51 Y: -5 Z: 216  (130)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
the moogle that gives out buffs and items only gave buff and a system message saying : An error occured, could not find the item ID. Please bug report

**Comment by TeoTwawki** [comment] 2017-12-12 21:11
duplicate of #1726

**Closed by TeoTwawki** 2017-12-12 21:11 UTC
Labels: Duplicate

**Comment by TeoTwawki** [comment] 2017-12-12 21:30
I have now modified the debug print. If it happens again, post to the existing issue.
