### ISSUE TITLE
Wingcutter +1 unequippable by NIN

### ISSUE THREAD

**Issue by Flamebuilt** [LegionDark/Issues#435] opened 2015-11-09 07:30 UTC
**Date & Time**: 11/9/2015 2:30 AM
**Frequency**: constant
**FFXI Client Version**:30150910_3
**Character Name**: Kabri
**Race**: HumeF
**Nation**: San d'Oria
**Main Job**: NIN
**Sub Job**: WAR
**Area & Coordinates**: n/a
**Party or Solo**: n/a
**NPC or Monster Name**: n/a
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/21350/wingcutter-1
**Multi-boxing? (multiple clients on same connection)**: yes
**Steps To Reproduce The Issue**: Tried zoning and changing jobs. Can't equip wingcutter +1 on NIN no matter what.

**Comment by Kaoriasada** [comment] 2015-11-10 22:18
This can't be equipped on THF either, and it has the correct job mask.  

INSERT INTO `item_armor` VALUES (21350,'wingcutter+1',99,119,4128,24,0,0,8,0);

I'm guessing the issue is because it's entered as "wingcutter+1" instead of "wingcutter_+1".  Sent to Loki.

**Comment by Kaoriasada** [comment] 2015-11-10 22:18
^Did not mean to close

**Comment by TeoTwawki** [comment] 2015-11-11 00:36
> entered as "wingcutter+1" instead of "wingcutter_+1".

yeah thats prolly why

**Comment by TeoTwawki** [comment] 2015-11-11 00:36
..I don't really know though

**Comment by Kaoriasada** [comment] 2015-11-11 02:03
OK, well that fix is what I sent to Loki.  Closing the issue.

**Closed by Kaoriasada** 2015-11-11 02:03 UTC
Labels: Todo: Item Not Coded / Incorrect Item Data
