### ISSUE TITLE
CoP No Access

### ISSUE THREAD

**Issue by Moeverick** [LegionDark/Issues#75] opened 2015-06-07 19:38 UTC
**6/1/15 12:00**: 
**Constant**:
**30150508_8**:
**Moeverick**:
**Hume**:
**Paladin**:
**Warrior**:
**Shattered Telepoints @ 3 Crags**:
**Party and Solo**:
**Shattered Telepoints**:
**NULL**:
**Had been in Spire of Dem BCNM and died prior. Went to reenter zone, telepoint shows normal message. CoP Mission @ 1-3, unable to enter any Promivion area. Mule (Goose) works fine. Spoke to all prior NPCs, still no reentry to any Promivion areas**:

**Comment by Tatako** [comment] 2015-06-09 02:07
Date & Time:  6/8/15
Frequency: Everytime
FFXI Client Version: _8
Character Name:  Tatako
Race:Mithra
Main Job: THF
Sub Job: DNC
Area & Coordinates: Mea, Dem, Holla Crags (Shattered Telepoints)
Party or Solo: either
NPC Name:n/a
Monster Name:n/a
Steps To Reproduce The Issue:  Trying to do CoP 1-3.  At all 3 crags when i click the telepoints i get the message:  "The telepoint has been shattered into a thousand pieces..."

This happened in party and solo and Blacken had the same issue at Mea but at Holla it let him in.
I have tried all 3 and they all said the same things.

I to have tried to do a promy solo (Holla) but died in the boss fight.  Spoke with all NPCs again and received the same message.

**Comment by atom0s** [comment] 2015-06-09 02:25
Please post your full client version. Shortening it does not help since many updates can end with _8.

**Comment by Tatako** [comment] 2015-06-09 02:56
Sorry will do.



On Jun 8, 2015, at 10:26 PM, atom0s <notifications@github.com<mailto:notifications@github.com>> wrote:


Please post your full client version. Shortening it does not help since many updates can end with _8.

-

**Comment by R3P0FFXI** [comment] 2015-06-17 14:50
Moverick and Tatako please contact me next time you are on if the standard fix did not work for you I will have to give you a KI to one of the 3 craigs to resolve your issue.

**Comment by Tatako** [comment] 2015-06-17 16:14
Will do thank you



On Jun 17, 2015, at 10:50 AM, R3P0FFXI <notifications@github.com<mailto:notifications@github.com>> wrote:


Moverick and Tatako please contact me next time you are on if the standard fix did not work for you I will have to give you a KI to one of the 3 craigs to resolve your issue.

-

**Comment by R3P0FFXI** [comment] 2015-06-21 02:05
Fixed for Tatako

**Comment by R3P0FFXI** [comment] 2015-07-02 11:58
Moverick is this still an issue I have not heard from you since resolving this for Tatako?

**Comment by Moeverick** [comment] 2015-07-02 14:25
I haven't been able to play much this week unfortunately, but I will check all 3 crags when I get home today and let you know immediately.

**Comment by Moeverick** [comment] 2015-07-04 05:17
The same issue remains for all 3 crags.

**Comment by Loki79** [comment] 2015-07-12 02:48
3p0 you get this fixed?

**Comment by Moeverick** [comment] 2015-07-12 04:57
He did get this fixed. Everything works fine now.

**Closed** 2015-07-12 12:40 UTC
Labels: Status: Resolved
