### ISSUE TITLE
Amhuluk not targetable

### ISSUE THREAD

**Issue by tb1** [LegionDark/Issues#1096] opened 2016-09-20 05:51 UTC
**Date & Time**: 
Sep 19 , 2016
11:45 MST

**FFXI Client Version (use `/ver`)**: 
30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes
60831_1

**Character Name**: 
tbone

**Nation**: 
windy

**Job(level)/Sub Job(level)**: 
PLD99/WAR

**NPC or Monster or item Name**: 
Amhuluk

**Zone name & Coordinates (use `$where`)**: 
X:20 Y:-15 Z:-51 (165)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
yes

**Steps To Reproduce / any other info**: 
Pop Amhuluk by normal means and try to target him.

He attacks you like normal, using his normal TP moves but you can't target him and attack back.

Amhuluk drops the empy base katana.

**Comment by R3P0FFXI** [comment] 2016-09-20 10:13
@TeoTwawki this is confirmed the mob pops in an untargetable state, before the mob used to pop in the sky and aggro players below. Now he just pops on the ground with no name or anything and stands in his location.

**Comment by TeoTwawki** [comment] 2016-09-20 13:20
Zone name wasn't included in the templated info like its supposed to be. I hate having to go perform a search to find wtf something even is - I don't memorize every mob in the game ya know..

This is a 5 min fix, I'll have him closed up shortly.

**Comment by TeoTwawki** [comment] 2016-09-20 13:24
In the future when someone "implements" a mob on this server, they should learn wtf the values they are copy&pasting even DO before committing it..He was given the no target and hide flags in his pool entry, because other Amphipteres have them.

**Comment by TeoTwawki** [comment] 2016-09-20 13:44
Hot-fixed by adding 
```lua
        GetMobByID(17662477):hideName(false);
        GetMobByID(17662477):untargetable(false);
``
to the script thats spawning the mob.

**Closed by TeoTwawki** 2016-09-20 13:44 UTC
Labels: Status: Escalation Needed / Has been Escalated

**Comment by TeoTwawki** [comment] 2016-10-05 05:43
@LegionDark I hate you #1142
