### ISSUE TITLE
Did not receive key item "Supplies Package" from missoin 1 of Treasures of Aht Urghan

### ISSUE THREAD

**Issue by Roamin** [LegionDark/Issues#210] opened 2015-08-04 20:05 UTC
**Date & Time**: august 4th 2015
**Frequency**: One time
**FFXI Client Version**: 30150619_2
**Character Name**: Thievan
**Race**: Elvaan
**Nation**: Windust
**Main Job**: Thief
**Sub Job**: Warrior
**Area & Coordinates**: Aht Urghan Whitegate
**Party or Solo**: Party
**NPC Name**: Naja Salaheem
**Monster Name**: not applicable
**Multi-boxing? (multiple clients on same connection)**: Yes 3 box same pc
**Steps To Reproduce The Issue**:
Talked with Naja Salaheem to start mission 1. Got cutscene approaching her door, telling me i have received a "Supplies Package"  Checked my KI and nothing, and the NPC will not tell me anything.  I tried talking to the NPC Mayeevaat I think the name is , at Ilrusi Atoll Staging Point , didnt say anything.  Used the runic portal to return to whitegate.

I had tried last night to use the Ilrusi Atoll Staging Point  to return home forgetting that i didnt have access yet, and it told me It can't let me pass.

**Comment by Kaoriasada** [comment] 2015-08-04 21:14
Didn't mean to assign myself.  But I gave him the KI and he's working fine now, however doesn't fix the issue that he didn't get it in the first place (probably caused by dualbox though)

**Comment by TeoTwawki** [comment] 2015-08-05 00:26
someone needs to create a test character, GM-warp him to whitegate and test the event without multi boxing (so 2 GM's will need to be involved). If its busted, tell DSP they broke it.

**Comment by Kaoriasada** [comment] 2015-08-05 00:58
Testing this with Kermit right now.  Gonna take some time because the quest starts with getting the boarding permit, and that's an in-game day wait.  

It's worth noting that some people are getting the KI, while others aren't.  People who weren't dualboxing have not gotten it as well.

**Comment by TeoTwawki** [comment] 2015-08-05 01:10
>  Gonna take some time because the quest starts with getting the boarding permit, and that's an in-game day wait. 

Thats why I suggested 2 GM's and one teleport the other over. Was pretty sure the boarding pass stuff doesn't actually count as part of the mission but is a pre-quest deal.

> It's worth noting that some people are getting the KI, while others aren't. People who weren't dualboxing have not gotten it as well.

But some *are* getting it? That's annoying, I wish things would be consistent in being *broken* or *not broken*. :facepunch: :beetle: 
If you can figure out what the people not getting it while not dual boxing have in common, super. :trophy: :+1:  
.
.
.
.
Ok yeah trying to see how many github emoji's I could legit cram into the same paragraph. Disappointing with myself that I didn't get farther lol.

**Comment by Kaoriasada** [comment] 2015-08-05 16:43
The boarding pass is counted as party of the quest!  We ran into our own issue on the damn mission where Kermit's alt (Kermit is an EGM btw) didn't get the CS, but he got pushed automatically to mission 2 with no KI.  Sooooso frustrating.  We're gonna try again with another character today.

**Comment by TeoTwawki** [comment] 2015-08-06 02:26
> The boarding pass is counted as party of the quest!

I think I know who effing changed that. I used to GM warp my GM characters there without getting the boarding pass and trip the CS at Naja's office without issue. But recently  much of the ToAU mission crap was broken by a moron who refuses to listen.

Players need to report all ToAU mission glitches from here out directly to DarkStar https://github.com/DarkstarProject/darkstar/issues/new
because I won't be touching those as long as that same editor still messes with them. His mess, he can clean it.

You don't have to keep investigating this, but if you do send it at DarkStars Tracker.

**Comment by TeoTwawki** [comment] 2015-08-06 02:29
@LegionDark/owners 
 p.s. pls don't link Legions issues in DSP's issues or link the DSP issue back here when it concerns these ToAU missions, I don't want TwuntWaffle waddling in here to post his nonsense in Legion's tracker.

**Comment by R3P0FFXI** [comment] 2015-08-07 23:37
https://github.com/DarkstarProject/darkstar/issues/1894

This is a DSP issue so we will be closing this as it will not be resolved until DSP fixes it

**Closed by R3P0FFXI** 2015-08-07 23:37 UTC
Labels: Status: Not Our Bug

**Comment by TeoTwawki** [comment] 2015-08-08 00:27
Super. Can't unlink this from DSP's issue R3 opened. I even deleted the comment here.
@R3P0FFXI If I have to deal with drama from anyone following that link into Legions tracker you will never hear the end of it. **NEVER EVER HEAR THE END OF IT.**

**Comment by TeoTwawki** [comment] 2016-04-01 00:40
https://github.com/DarkstarProject/darkstar/pull/2960
