### ISSUE TITLE
Can't equip Pamun item (not Su1 or Su2)

### ISSUE THREAD

**Issue by Nususu** [LegionDark/Issues#971] opened 2016-06-11 21:02 UTC
**Date & Time**: 6/11/16 5pm EST

**FFXI Client Version (use `/ver`)**: 30160427_0

**Character Name**: Nususu

**Nation**: Bastok

**Job(level)/Sub Job(level)**: NIN99/WAR49

**NPC or Monster or item Name**: Pamun

**Zone name & Coordinates (use `@where`)**: N/A

**ffxiah.com link (for items issues only)**: http://www.ffxiah.com/item/21006/pamun

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps To Reproduce / any other info**: Had someone synth Pamun for me, can't equip it. Item is white in equip screen indicating it should equip, but it doesn't. "Downloading Data" flashes on the top of screen. I have attached screenshot. The item does not have Su1 or Su2 tags, which as far as I knew were the only non equipable items currently.

<img width="683" alt="screen shot 2016-06-11 at 3 00 07 pm" src="https://cloud.githubusercontent.com/assets/19480479/15987428/6124738c-2fe5-11e6-9198-ecd59027a5c0.png">

**Comment by Genesis-Legion** [comment] 2016-06-11 21:04
It's a known issue that Su items can't be equipped atm, it's currently being worked on.

**Comment by Nususu** [comment] 2016-06-11 21:09
Sorry if my post wasn't clear, it's not a Su item.

On Sat, Jun 11, 2016 at 3:04 PM, Genesis <notifications@github.com> wrote:

> It's a known issue that Su items can't be equipped atm, it's currently
> being worked on.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/LegionDark/Issues/issues/971#issuecomment-225394091>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASk_n7lyAx3pfJqcTqrj15WnggDu4qgLks5qKyLvgaJpZM4IzpFG>
> .
>



-- 
Dylan Shearer
Marriott School of Management | Brigham Young University
mobile: (508) 314-9892 | sdshearer26@gmail.com
LinkedIn: www.linkedin.com/in/shearerdylan

**Comment by Nususu** [comment] 2016-06-15 12:16
I have done more testing on the issue. I tried equipping the Pamun while fighting. It didn't equip, but it did erase my TP as if I had equipped a different weapon. Not sure if that's helpful, but just wanted to give as much information as I could.

**Comment by Samikana** [comment] 2016-06-17 13:36
It's because it doesn't have an entry in probably item_basic.

**Comment by R3P0FFXI** [comment] 2016-06-17 13:40
@Samikana 

INSERT INTO `item_basic` VALUES (21006,0,'pamun','pamun',1,2084,9,1,0);
INSERT INTO `item_basic` VALUES (21007,0,'pamun_+1','pamun_+1',1,2080,9,1,0);

INSERT INTO `item_armor` VALUES (21006,'pamun',99,117,4096,0,0,0,3,0);
INSERT INTO `item_armor` VALUES (21007,'pamun_+1',99,118,4096,0,0,0,3,0);

INSERT INTO `item_weapon` VALUES (21006,'pamun',9,0,203,203,167,2,1,242,124,0);
INSERT INTO `item_weapon` VALUES (21007,'pamun_+1',9,0,215,215,177,2,1,234,125,0);

Can you test please and see if you can equip the +1 version im at work and cannot test, above is what is in the database currently.

**Comment by R3P0FFXI** [comment] 2016-06-18 14:24
@Samikana @Genesis-Legion I can confirm Pamun and Pamun +1 both cannot be equipped

**Comment by Samikana** [comment] 2016-06-24 02:50
@R3P0FFXI not sure when I'll have time.  Closest day I'll have free is July 7th.  I'm swamped with work and class until then, I'll do my best to try and check when I have a second.

**Comment by PikaFox** [comment] 2016-06-24 16:05
The only thing i can see wrong with the item basic is that the first Pamun is 2084 instead of 2080 (inscribable + equipable 32 + 2048), other than that it looks fine.

**Comment by Nususu** [comment] 2016-06-29 19:52
Depending on what the learning curve is like, I would be happy to help maintain/correct/update things like this in the item databases. Have some coding and database experience.

**Comment by Nususu** [comment] 2016-07-07 22:46
Hi @Samikana , any luck with this today? No rush at all, just wanted to check in. Thanks!

**Comment by PikaFox** [comment] 2016-07-08 19:04
Changes to items will usually be done when the next server maintenance occurs. I dont know when this will be, but that should likely give you a general idea as to when a change may occur, assuming one is made.

**Comment by Nususu** [comment] 2016-07-08 19:18
@pikafox thank you for the clarification.

**Comment by atom0s** [comment] 2016-09-18 06:09
Should be fixed now, just tested and can equip the weapon. However, the item does not appear to have any mods currently. @LegionDark/thebosses

**Comment by R3P0FFXI** [comment] 2016-10-12 07:12
Issue resolved in Maint

**Closed by R3P0FFXI** 2016-10-12 07:12 UTC
Labels: Todo: Incorrect or missing Item Data
