### ISSUE TITLE
Inventory Glitch

### ISSUE THREAD

**Issue by Divineangel** [LegionDark/Issues#1244] opened 2016-11-21 22:22 UTC
**Date & Time**: 11/21/2016

**FFXI Client Version (use `/ver`)**: 30161004_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  Yes

**Character Name**: Divineangel and Kazzan (two separate account)

**Nation**: San d'Oria

**Job(level)/Sub Job(level)**: BLU99/RDM49

**NPC or Monster or item Name**: N/A

**Zone name**: N/A

**Coordinates (use `$where`)**: N/A

**ffxiah.com link (for items issues only)**: N/A

**Multi-boxing? (multiple clients on same connection)**: Either way Multi- Boxing or not

**Steps To Reproduce / any other info**: 
server transfer issue - i have a problem with my inventory when its at 15/80 i cant obtain any more items in my inventory. i cant even move items from other spots aka Safe, satchel, etc... when i am at 15/80. please help me with my inventory issues.

**Comment by R3P0FFXI** [comment] 2016-11-26 16:31
@Divineangel if you transferred 2 accounts via server transfer we will rectify only 1 of them as migrating 2 accounts is against the server TOS. Let me know which account you want fixed and we can start going through your inventory on a test account to see where the issue is.

**Comment by R3P0FFXI** [comment] 2016-12-06 12:10
No response from user closing

**Closed by R3P0FFXI** 2016-12-06 12:10 UTC
