### ISSUE TITLE
Corpselights family crashing PoL

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#841] opened 2016-04-06 22:42 UTC
**Date & Time**: Wednesday April 6th, 2016

**FFXI Client Version (use `/ver`)**: na/current?

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Blu99/rdm49

**NPC or Monster or item Name**: Corpselights family, specifically Dybbuk in aby konsch and Caoinegg in aby tarongi

**Zone name & Coordinates (use `@where`)**: F6 flux 4 x: -316.186, y: 8.151, z: 272.982

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: 90% sure whenever the mob casts the move Thundris shriek PoL crashes, the move hell cap could also be a trigger to crash PoL.

**Comment by TeoTwawki** [comment] 2016-04-06 23:30
nope, not it, but will investigate to see what is doing it.

**Comment by TeoTwawki** [comment] 2016-04-26 01:12
Determined to have most likely been caused by a player action that will be fixed in next maint.

**Closed by TeoTwawki** 2016-04-26 01:12 UTC
