### ISSUE TITLE
Mandau Trial too broke, sorry.

### ISSUE THREAD

**Issue by Genesius1490** [LegionDark/Issues#502] opened 2016-01-11 22:24 UTC
**Date & Time**: Monday 11/01/2016 -- 10pm GMT
**Frequency**: Always
**FFXI Client Version**: 30151204_2
**Character Name**: Genesius
**Race**: Hume Male
**Nation**: Bastok
**Main Job**: THF
**Sub Job**: DNC
**Area & Coordinates**: Valley of Sorrow / Behemoth's Dominions 
**Party or Solo**: Party
**NPC or Monster Name**: Adamantoise/Behemoth/Fafnir
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:  Yes, Genesius (THF) + Jenna (WHM)

Issue: Trial ID: 18638 Not getting credits for Mandau relic trial. screenshots above:
http://imgur.com/a/gkKar

**Comment by TeoTwawki** [comment] 2016-01-11 22:47
By chance do you have another item for which trials exist equipped in a separate slot at the time, like a mythic in your offhand? I'm trying to find something in common among ppl who are experiencing this problem.

**Comment by Genesius1490** [comment] 2016-01-11 22:53
I have no other trial on Genesius, though I have Yagrush trial started on Jenna.

**Comment by TeoTwawki** [comment] 2016-01-11 23:06
clarification: I'm not asking if you have other active trials (currently possible) I'm asking if you had any equipment that is trial-capable.

**Comment by TeoTwawki** [comment] 2016-01-11 23:26
@Genesius1490 I have found and fixed the cause.

@Samikana folks who have been killing NQ and HQ land kings who have issue reports opened stating they received no credit can be manually adjusted by setting their variables.
```lua
C_TRIAL_OBJ_1
C_TRIAL_OBJ_2
C_TRIAL_OBJ_3
C_TRIAL_OBJ_4
C_TRIAL_OBJ_5
C_TRIAL_OBJ_6
```
Are the variables involved, each one corresponds to a specific monsters kills count.

@R3P0FFXI checking the server log would have shown you what was wrong.

**Comment by TeoTwawki** [comment] 2016-01-11 23:28
#498 and #499 are the same issue. All can be closed ones those who already posted are credited. No posts that happen after this get credited, they can re-kill. Its fixed in live right now.

**Comment by Samikana** [comment] 2016-01-12 12:23
@TeoTwawki I'll do this today

**Comment by Samikana** [comment] 2016-01-16 16:55
@Genesius1490 please send Halsey a tell in-game and in the meantime I'll update your trial for you.  I've sent you a tell twice in the last two days in-game with no response so I will now be waiting for you to reach out

**Closed** 2016-01-18 19:44 UTC
