### ISSUE TITLE
Level Sync Breaking Again

### ISSUE THREAD

**Issue by PikaFox** [LegionDark/Issues#1095] opened 2016-09-20 02:00 UTC
**Date & Time**: 9/19/16

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: Yes

**Character Name**: Nyaarun

**Nation**: Win

**Job(level)/Sub Job(level)**: was around 34ish drg

**NPC or Monster or item Name**: NA

**Zone name & Coordinates (use `$where`)**: Crawler's Nest

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: 
Unknown exactly what triggered it. Happened twice in party, party leader doesnt know what caused it as well. Only things of note i can mention is the party leader died without signet on and got raised once, and the party leader ended up zoning another time.

**Comment by R3P0FFXI** [comment] 2016-09-20 02:02
@PikaFox Did the party leader cross server lines? IE go to Whitegate when he HP, then back to say Abyssea?

**Comment by PikaFox** [comment] 2016-09-20 02:03
No. Crawlers Nest > Rolanberry > Crawler's Nest once.

**Comment by PikaFox** [comment] 2016-09-20 02:04
Also worth mentioning, the sync worked as intended, even though broken (red dot wasnt on the sync designee) until the sync target left, then it capped everyone at the level they were at before they left, similar to the issues that happened before when it broke.

**Comment by TeoTwawki** [comment] 2016-09-20 02:05
Server is on latest DSP core revision now, so best to make sure the issue is on their tracker (their may be an open one already, if so we shoudl add any info they don't already have).

**Comment by PikaFox** [comment] 2016-09-20 02:07
I believe the party leader was duaboxing at the time and had another char in abyssea, if thats relevant.

**Comment by TeoTwawki** [comment] 2016-09-20 02:08
Might be. But probably not since same map server. Worth trying to see if we can make it happen on purpose.

**Comment by PikaFox** [comment] 2016-09-21 19:37
It seems that level sync "breaks" just by using it. The red dot never appears next to the syncee, meaning that whenever they leave the party will always be perma synced to the syncees level.

**Comment by Jessland86** [comment] 2017-08-28 12:41
This has been resolved in the last maintenance.

**Closed by Jessland86** 2017-08-28 12:41 UTC
Labels: DSP's issue : either unimplemented feature or bugged from their side, Escalation Needed / Has been Escalated
