### ISSUE TITLE
Incorrect Choice Values for CoP Ring Reward Dialog

### ISSUE THREAD

**Issue by Daruvan** [LegionDark/Issues#1413] opened 2017-03-12 15:44 UTC
**Date & Time**: March 12th, 2017, 10:43 AM

**FFXI Client Version (use `/ver`)**: 30170204_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Daru

**Nation**: Windurst

**Job(level)/Sub Job(level)**: THF99 / DNC49

**NPC or Monster or item Name**: Door: "Marble Bridge"

**Zone name**: Upper Jeuno

**Coordinates (use `$where`)**: X: -95 Y: 0 Z:91 (113)

**ffxiah.com link (for items issues only)**: -

**Multi-boxing? (multiple clients on same connection)**: No

**Steps To Reproduce / any other info**: Entered cutscene for choice of reward, and Tamas Ring displayed twice in choices, one in placeholder for Rajas:
![daru_2017 03 12_104344](https://cloud.githubusercontent.com/assets/21298141/23833211/d64c3054-0718-11e7-8b83-e274d310cb2a.png)

**- Changing zones and re-entering cutscene provided expected choices.**

**Comment by JessLand86** [comment] 2017-03-12 16:07
I noticed this happened for the Divine Might reward as well. Mine was caused by going into an item to look at the stats and then choosing "no" and viewing another item.

**Comment by Heepster03** [comment] 2017-03-13 14:23
I just did this quest last week and it said Rajas Ring. Because I chose it.

**Comment by Heepster03** [comment] 2017-03-13 17:38
![halkuras_2017 03 13_123424](https://cloud.githubusercontent.com/assets/8421725/23867416/cdc6411e-07e9-11e7-97dc-cf6b9b56afaa.png)

^ That was me giving trying to reproduce it on _[GM] Halkuras_ and as you can see, it is working as intended.

**Comment by Heepster03** [comment] 2017-03-13 20:37
I have reproduced the bug and put a report into DSP. If this happens to you, just back out fully and go back in. 

https://github.com/DarkstarProject/darkstar/issues/3801

**Comment by R3P0FFXI** [comment] 2017-05-12 00:16
@Daruvan issue resolved in todays update

**Closed by R3P0FFXI** 2017-05-12 00:16 UTC
Labels: DSP problem: Not our bug / Not Implemented, Fix Submitted to DSP
