### ISSUE TITLE
Unable to submit new Guild Points after first turn in.

### ISSUE THREAD

**Issue by neuromancerxi** [LegionDark/Issues#409] opened 2015-10-27 15:23 UTC
**Date & Time**: 2015-10-27, 11:15 AM Eastern
**Frequency**: Repeatable
**FFXI Client Version**: 30150910_3
**Character Name**: Neuromancer
**Race**: Taru
**Nation**: Sando
**Main Job**: WAR
**Sub Job**: THF
**Area & Coordinates**: Bastok Markets Goldsmithing (H-8)
**Party or Solo**: Solo
**NPC or Monster Name**: Ellard (Goldsmithing GP NPC)
**ffxiah.com link (for inventory items only)**: varies (see below)
**Multi-boxing? (multiple clients on same connection)**: No
**Steps To Reproduce The Issue**: 

Issue appeared after submitting my first GP item turn in. I thought this might have something to do with the client/version difference. After server update this AM, problem persists.

NPC will give me dialog about current GP item, but I am unable to turn in the current item. Information about my current limits is always "You are not eligible to receive guild points at this time." I have tried submitting on different Earth days and game days with the same results.

**Comment by R3P0FFXI** [comment] 2015-10-27 15:47
This is a old DSP bug not sure if it has been resolved in DSP yet or not

**Comment by neuromancerxi** [comment] 2015-11-06 19:13
On a whim checked GP NPC this morning, and was able to turn in GP item. Will check again tomorrow after server midnight and see if I can continue to turn in.

**Comment by TeoTwawki** [comment] 2015-11-07 03:10
Sounds like you hit the bug I mentioned on the Legion forum last night http://www.legiondark.com/forums/viewtopic.php?f=13&t=1104#p3474

**Comment by neuromancerxi** [comment] 2015-11-11 16:12
I thought it might have been related to JP / EST midnight, but the issue persisted over a number of days (5+). I have been able to submit GP consistently the last few days without issue. 

The only thing that changed between the issue appearing and submission becoming available again that comes to mind (minus server restarts) was I visited the clothcrafting guild, and it treated me as if I had never signed up. I signed up with the CC guild again. When I returned to the GS guild to check if I could submit GP items, it allowed me to do so. 

Not sure if there is a flag that got reset when I did this, or if its some other mechanic.

**Comment by TeoTwawki** [comment] 2015-11-11 22:44
>  but the issue persisted over a number of days (5+)

Start tracking the time of day (earth time) and date when this happens. I'll check sever up-time near/during the occurrences.

> I visited the clothcrafting guild, and it treated me as if I had never signed up.

for that as well.

**Comment by neuromancerxi** [comment] 2015-11-13 16:50
2 more days of submissions, both successful. I am now waiting until after JP midnight before checking/submitting GP. 

I have also visited Leatherworking Guild and did not encounter the never signed up issue.

I will continue to monitor and report back.

**Comment by R3P0FFXI** [comment] 2016-03-16 18:00
Reopen if still an issue after update

**Closed by R3P0FFXI** 2016-03-16 18:00 UTC
Labels: DSP problem: Not our bug / Not Implemented, on hold for "huge refactor of all custom things" update

**Comment by iwaswinjafirst** [comment] 2017-10-10 20:51
there's a limit to how many points you can turn in at a given time. its not a bug

**Comment by TeoTwawki** [comment] 2017-10-10 22:15
This was closed back in march. why am I getting notifications on it now?

Also, we know what the limits are, that wasn't what the problem was.
