### ISSUE TITLE
Voidwrought T4 Windy VWNM freezing PoL

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#885] opened 2016-04-21 21:25 UTC
**Date & Time**: April 21st, 2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Blu99/Rdm49

**NPC or Monster or item Name**: Voidwrought

**Zone name & Coordinates (use `@where`)**: Outer Horutoto Ruins

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: Voidwrought opened with dispelga and 3 people locked up at the beginning of fight.  We popped multiple times and it happened a few other times after that as well.  Also took a screenshot. 

http://i.imgur.com/01jo2sX.jpg

**Comment by R3P0FFXI** [comment] 2016-04-22 01:16
@spectre99 No if you see the ability go off its not the cause of the crash if there even is one. Most likely you or one of the 3 others are a Blu mage and one of those spells is causing your issue. It is not VWNM.

**Comment by TeoTwawki** [comment] 2016-04-22 03:06
@R3P0FFXI I wasn't done with this yet, had already tagged it as being investigated

**Comment by TeoTwawki** [comment] 2016-04-22 03:55
As expected dispelga on the server is fine, however a lot of ppl are seeing the newer xiloader packed with ashita crashing at odd times (I am told servo is crashing). I suggest reporting exact crash circumstances to ashita's tracker, if one is using ashita+the loader it came with.

Re-closing this, because ether isn't anything more I can do with it without more info. If you find out anything more @spectre99 you may post it here even though this is closed - I'll still see it.

**Closed by TeoTwawki** 2016-04-22 03:55 UTC
Labels: Status: Investigation / Work In Progress

**Comment by TeoTwawki** [comment] 2016-04-26 01:14
Determined to have most likely been caused by a player action that will be fixed in next maint.
