### ISSUE TITLE
Ghost Items inventory

### ISSUE THREAD

**Issue by nemesisx101** [LegionDark/Issues#463] opened 2015-12-10 02:11 UTC
**Date & Time**: December, 9th ,2015
**Frequency**:Always
**FFXI Client Version**:30151103_3
**Character Name**:Lightnote
**Race**:Hume
**Nation**:Bastok
**Main Job**:Bard
**Sub Job**:Whitemage
**Area & Coordinates**:Bastok Mines
**Party or Solo**: Party
**NPC or Monster Name**:NA
**ffxiah.com link (for inventory items only):** 
http://www.ffxiah.com/item/4996/mages-ballad-iii
http://www.ffxiah.com/item/5006/valor-minuet-v 
http://www.ffxiah.com/item/5079/foe-lullaby-ii
**Multi-boxing? (multiple clients on same connection)**:NA
**Steps To Reproduce The Issue**: Tried Sorting and Repurchasing items: Foe Lullaby II, 
Mage's Ballad III, Valor Minuet V.

**Comment by Samikana** [comment] 2015-12-10 14:21
Do you need to learn these scrolls?  Someone else will have to fix the issues with the ghost items, but I can use commands and add the songs to your cast list.

**Comment by nemesisx101** [comment] 2015-12-10 15:12
Yes I need to learn them

**Comment by Samikana** [comment] 2015-12-10 18:20
Will you be on at 9PM EST?

**Comment by TeoTwawki** [comment] 2015-12-10 22:36
The stuck items have been manually removed from the characters inventory. This appears to not be eh same bug I was expecting, but a new one.

@Samikana see if you can give him new copies of the items before handing him the spells directly. Make sure he has free space first of course.

**Comment by TeoTwawki** [comment] 2015-12-10 22:38
Just confirmed my suspicious: characters with items in retails second mogsafe will get stuck items, requiring the removal of those items or moving them to a different container with enough free space.

**Comment by TeoTwawki** [comment] 2015-12-10 22:39
Its because DSP hasn't fully implemented the 2nd mogsafe yet.

**Comment by Samikana** [comment] 2015-12-11 22:10
I need to know a time you'll be online when I can help you figure this out.

**Comment by Samikana** [comment] 2015-12-14 13:32
Closing this.  No player response.

**Closed by Samikana** 2015-12-14 13:32 UTC
Labels: Status: Escalation Needed / Has been Escalated
