### ISSUE TITLE
Windurst Mission 2-3

### ISSUE THREAD

**Issue by Gigas0813** [LegionDark/Issues#472] opened 2015-12-19 06:34 UTC
**Date & Time:  12/19/15 12:20 am Central standard
**Frequency: twice 
**FFXI Client Version: Version 30151204_2
**Character Name:  Neferpitou
**Race: Mithra
**Nation: Windurst
**Main Job: Rdm
**Sub Job: Nin
**Area & Coordinates:  X: 339 Y: -115 Z: 256 (193).
**Party or Solo: Party of 2
**NPC or Monster Name: Seeker and Dark Dragon 
**Multi-boxing?: No
**Steps To Reproduce The Issue**:  My first attempt was solo and I died so I got a friend to help.  we entered and defeated the monsters and the cut scene after the fight froze after the first line.  The seeker says this cannot be.  me defeated by these weaklings?! and nothing else happens after that.  I was left in suspense.  that happened yesterday 12/18/15 around 1am or so.  I tried again today and my friend left the party after entering the fight to see if that made a difference.  The exact same thing happened after the monsters were defeated and the cut scene started.   

Thanks.

**Comment by TeoTwawki** [comment] 2015-12-19 06:36
your client version is newer than server version, once we update your cs will no longer be calling the wrong NPCs which causes it to freeze.

**Comment by TeoTwawki** [comment] 2015-12-19 06:40
There may be a secondary cause as  #459 seems to be same problem but they are on the November client (perhaps an ID was wrong even before the December client update, it happens from time to time).

A GM in game may contact you to just push you past it soon, will be their call.

**Comment by R3P0FFXI** [comment] 2015-12-19 11:26
@Samikana please push character past cs

**Comment by Gigas0813** [comment] 2015-12-19 12:33
nobody contacted me but I will be on tonight.  Is it okay to ask a gm If one is online?
Thanks for the help!

**Comment by Samikana** [comment] 2015-12-19 14:26
I was sleepin dawg

I'll push you past

**Comment by Gigas0813** [comment] 2015-12-20 06:07
oh haha okay.  so i have to be online or what?

**Comment by Samikana** [comment] 2015-12-20 14:01
Yes

**Comment by Gigas0813** [comment] 2015-12-20 22:21
okay well im online now.  I'll probably head out and just leave it logged on till I'm home unless it disconnects from me being away.  I will be on in the evening also

**Comment by Samikana** [comment] 2015-12-21 12:23
@Gigas0813 you should be all fixed up.  Keeping this opened until it actually gets fixed.

**Comment by Samikana** [comment] 2015-12-21 20:59
@BeguZoo let me know here when you can get in-game and I'll push you past.

**Comment by TeoTwawki** [comment] 2015-12-22 10:59
Confirmed NPC ID issue. Will be fixed in update.

**Closed** 2016-02-25 20:42 UTC
Labels: on hold for "huge refactor of all custom things" update, Status: Investigation / Work In Progress, Status: Player Reply Required
