### ISSUE TITLE
Head Butt and Sudden Lunge causing pol crashes on Ushumgal

### ISSUE THREAD

**Issue by Genesis-Legion** [LegionDark/Issues#904] opened 2016-04-25 07:35 UTC
**Date & Time**: 2:24 am

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Azazel

**Nation**: Bastok

**Job(level)/Sub Job(level)**: BLU99/RDM49

**NPC or Monster or item Name**: Ushumgal

**Zone name & Coordinates (use `@where`)**: North Gustaberg [S] @ X: 798, Y: 0, Z: 439 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: No. Was solo.

**Steps To Reproduce / any other info**: 
Following up on issue #897 about an hour+ testing (and many crashes with both headbutt and sudden lunge) I figured what I've found would be best suited posted here.
I had consistent pol crashes stunning Ushumgal's TP moves with both headbutt and sudden lunge.

(Edit)
I didn't get a pol crash fighting any other bastok vwnms multiple times with either stun.

[Ushumgal] Grim Glower ¨ Azazel
[Azazel] 186 Sudden Lunge ¨ Ushumgal
=== Area: North Gustaberg [S] === <- (every one of these lines is me coming back from a crash)

[Ushumgal] Aqua Fortis ¨ Azazel
[Azazel] 25 Sudden Lunge ¨ Ushumgal
=== Area: North Gustaberg [S] ===

[Ushumgal] Regurgitation ¨ Azazel
[Azazel] 3 Head Butt ¨ Ushumgal
=== Area: North Gustaberg [S] ===

[Ushumgal] Calcifying Mist ¨ Azazel
[Azazel] 177 Sudden Lunge ¨ Ushumgal
=== Area: North Gustaberg [S] ===

[Ushumgal] Grim Glower ¨ Azazel
[Azazel] 4 Head Butt ¨ Ushumgal
=== Area: North Gustaberg [S] ===

[Ushumgal] Delta Thrust ¨ Azazel
[Azazel] 243 Sudden Lunge ¨ Ushumgal
=== Area: North Gustaberg [S] ===

**Comment by TeoTwawki** [comment] 2016-04-25 19:17
The blue magic spells are likely involved, but the mob not. This type of thing wouldn't work in a way that only happened at one mob. I'm looking into a possible problem with the message sent to the client.

**Comment by TeoTwawki** [comment] 2016-04-26 01:12
Determined to have most likely been caused by a player action that will be fixed in next maint.

**Closed by TeoTwawki** 2016-04-26 01:12 UTC
