### ISSUE TITLE
Rending Deluge blu spell

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#891] opened 2016-04-22 19:13 UTC
**Date & Time**: Friday April 22nd 2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Blu99/rdm49

**NPC or Monster or item Name**: RAVENOUS CRACKLAW

**Zone name & Coordinates (use `@where`)**: Purgonorgo Isle 

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: This spell used to be learnable from Ravenous Cracklaw.  He is fixed now and acts normally so we went out there with about 11 or 12 people.  We fought him, and it did the move, but none of the 6 blus learned the spell.  After I checked the blue spell tool on the website and the spell was missing from the list.  Rending Deluge is just one of the spells that used to be learnable but now has disappeared.  Teo said to make a report.  I can go through some of the other blu spells and make one big report or make individual reports per spell.

**Comment by TeoTwawki** [comment] 2016-04-22 20:09
I've found the issue, and it effects the following spells:
_Nature's Meditation
Tempestuous Upheaval
Rending Deluge
Embalming Earth
Paralyzing Triad
Foul Waters
Glutinous Dart
Retinal Glare
Subduction
Thrashing Assault
Erratic Flutter
Restoral
Rail Cannon
Diffusion Ray
Sinker Drill_
This was caused by a combination Legion not staying on top of pull requesting things that were fixed for blue magic, and not putting non darsktar content into a custom file (so the changed were lost when I didn't look for custom things in files that shouldn't have anything custom in them, during massive update part 1).

This will be fixed with the next server maintenance.

**Closed** 2016-04-23 00:10 UTC
