### ISSUE TITLE
Problems with Celaeno T4 Bastok VW

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#868] opened 2016-04-16 13:58 UTC
**Date & Time**: Friday april 15th, 2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Blu99/rdm49

**NPC or Monster or item Name**: Celaeno

**Zone name & Coordinates (use `@where`)**: Dangruf Wadi

**ffxiah.com link (for items issues only)**: no

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: 

Problem 1.  Whoever beats Celaeno gets a TON of merits, everyone else gets less than 600 exp merits.  Rydia beat it the first time.  Here is a screenshot.  http://i.imgur.com/NfSkQhs.png  Rydia beat it again and got just as many merits, another screenshot: http://i.imgur.com/aU4cXhC.png

Problem 2.  The person who popped had a t4 abyssite on both characters, after defeating Celaeno his abyssite didn't change on either character.  Character's name is Hickss and his healer mule who also had t4 is kimmi I believe.  He went to the conflux in pash anyway to see if he would get the upgrade since Bastok t4 was his last boss he needed, this is a screenshot of the error message he got.  http://i.imgur.com/3LfSyks.png  (additional screenshot he took after defeating Celaeno that shows his abbysite didn't change even though he was the one that popped http://i.imgur.com/5VtbIWs.png )

**Comment by Samikana** [comment] 2016-04-16 15:51
Well, first off, spamming it isn't going to help your variable change lol.

I'll go test the EXP thing.

**Comment by Samikana** [comment] 2016-04-16 16:09
@TeoTwawki it seems to me that the EXP is based off of how many characters are in the party and it goes to the person who has the last hit.

In their screenshot, Rydia got over 30 merit points.  Woah.  But when I tested it, I had 3 characters in my party and I only got about 7 merits.

**Comment by R3P0FFXI** [comment] 2016-04-16 16:44
@spectre99 T4 Abyssite isn't going to change you need to follow the questline to progress we have said this numerous times this is working as intended.

**Comment by spectre99** [comment] 2016-04-16 16:56
The t4 abyssite is supposed to change back to a t1 after you beat the boss isn't it? I mean that is what happened to me.  For Hickss he was able to pop the t4, but when he beat the boss the abyssite didn't reset back to 1. He had gotten the other city clears so it was the last one he needed before getting the cutscenes to get jeuno access. So after he beat bastok t4 he tried to continue with the quest line as hes supposed to, but was unable to get cs.

**Comment by R3P0FFXI** [comment] 2016-04-16 17:09
@spectre99 I am positive the abyssite changes after you go to upgrade to the white abyssite, you need all 3 T4 abyssites to upgrade to White T1 via quest.

**Comment by spectre99** [comment] 2016-04-16 17:13
Again, that isn't what happened to me, for me all of the t4 abyssites reset back to 1 after I beat the boss.  When I went to get the cutscene in Pashh[s] all my abyssites were 1, and I was able to get the cs, and got the white abyssite afterwards.  The screenshot that hickss sent me, he had already beaten windy/sandy t4 bosses, which is why the abyssites showed as t1.  For whatever reason, for him the win didn't register.

**Comment by TeoTwawki** [comment] 2016-04-16 17:19
@R3P0FFXI remember when I got all mad about renaming some scripts in windows instead of git and deleting a duplicate in dangruf wadi? This was from that. One version of the script was an older one, before the killer/ally change. So everything went onto 1 person (killer) instead of everyone (ally)

**Comment by TeoTwawki** [comment] 2016-04-16 17:27
meant to comment, not comment+close

the bug is now fixed in code, I leave it to r3 to do whatever with vars and KIs

**Comment by Samikana** [comment] 2016-04-23 00:38
@R3P0FFXI The issue with people's wasted stones and fights needs to be addressed, or you need to leave some sort of instructions on how to fix it so that somebody else can address the issue.

Teo n Sami callin not it bruh

**Closed** 2016-04-26 01:15 UTC
