### ISSUE TITLE
Heka's kalasiris not working right

### ISSUE THREAD

**Issue by puffer1221** [LegionDark/Issues#284] opened 2015-09-04 13:47 UTC
**Date & Time**: 14:40 pm gmt, 4/9/2015
**Frequency**: constant
**FFXI Client Version**: 30150730_1
**Character Name**: Anofrei
**Race**: Taru
**Nation**: Bastock
**Main Job**: Whm
**Sub Job**: Rdm
**Area & Coordinates**: Irrelevant
**Party or Solo**: solo or party
**NPC or Monster Name**: irrelevant
**ffxiah.com link (for inventory items only)**: http://www.ffxiah.com/item/11867/hekas-kalasiris , http://www.ffxiah.com/item/10865/nefer-khat
**Multi-boxing? (multiple clients on same connection)**: irrelevant
**Steps To Reproduce The Issue**: Equip the heka and nefer khat and the set bonus of refresh doesnt activate, same result from equipping the nefer khat +1.

**Comment by R3P0FFXI** [comment] 2015-09-05 00:42
Set bonuses are being worked on in DSP this will be added whenever DSP gets around to adding it

**Comment by TeoTwawki** [comment] 2015-09-05 00:43
This looks like a duplicate of #273

**Comment by TeoTwawki** [comment] 2015-09-05 00:44
And #244

**Comment by TeoTwawki** [comment] 2015-09-05 00:44
Leaving open till after maint so people stop posting it.

**Comment by TeoTwawki** [comment] 2015-09-05 00:45
And if the maint doesn't fix it, then there is a bug to report to DSP.

**Comment by excenmille** [comment] 2015-09-16 04:58
The Refresh set bonus has been working since the Sept maintenance that required us to update our client.

**Comment by R3P0FFXI** [comment] 2015-09-16 17:09
What client update there was no Legion Client update???

**Comment by TeoTwawki** [comment] 2015-09-16 19:32
its fixed since last maint in any case, closing

**Closed by TeoTwawki** 2015-09-16 19:32 UTC
Labels: DSP problem: Not our bug / Not Implemented, Status: Duplicate
