### ISSUE TITLE
Key items lost..... again ; ;

### ISSUE THREAD

**Issue by stevomatic** [LegionDark/Issues#1471] opened 2017-05-10 06:40 UTC
**Date & Time**: 5/10/2017 roughly 1:30am EST

**FFXI Client Version (use `/ver`)**: 30170304_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: yes

**Character Name**: Agnes

**Nation**: Bastok

**Job(level)/Sub Job(level)**: nin99/war49

**NPC or Monster or item Name**: 

**Zone name**: Was at Mount Zhayolm zoning into Halvung when I checked my map and noticed their absence

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: yes I had my mules Annebonnie on desktop with me, Langridge and Gurgitator on my laptop

**Steps To Reproduce / any other info**: Not sure when it happened, I was mostly focusing on mule today. Was running around ToAU areas doing znm when I noticed. Coming out of Halvung staging point I got 'another event called' message in log exiting the staging point gate, that's the only remarkable thing I can think of. I logged in with Agnes roughly 3pm EST 5/9/17 so before that the KI's would have been there. I checked KI's for mules and they're all there. I just saw the kujaku katana model on another character and it displays differently than the one I used on Agnes which appeared as the sai model. It made me think that when i first started i tried a magian katana and that wouldn't display and also left some KI in my inventory that I couldn't seem to get rid of iirc. Speaking of Black Coffin, before that last change made to it, I tried periodically to do the mission which was stuck stuck in a weird loop and the ephramadian coin KI was jacked up

**Comment by TeoTwawki** [comment] 2017-05-16 00:53
Should be re-fixed now

**Comment by TeoTwawki** [comment] 2017-05-16 00:55
> Coming out of Halvung staging point I got 'another event called' message in log exiting the staging point gate

you mean on going through the doors or what?

**Comment by stevomatic** [comment] 2017-05-16 01:08
looks like they're there, thank you.  Staging point, yes after taking the runic portal to halvung staging point, the gate you have to pass through into the zone.  You have to click on the gate to leave the staging point, answer 'yes,' then you get the zoning cutscene before you're free to proceed

**Comment by TeoTwawki** [comment] 2017-05-16 21:59
hadn't closed this yet because trying to figure out how it happened first..ruled out the magian stuff no KI probs in those scripts. rules out the gate being the cause, could not reproduce the interrupt message but did wipe the returns out of it (maybe the returns borked lua stack for alts, dunno). Only thing left for me to do is run black coffin a few times see if I can jack up my KI's from that.

**Comment by TeoTwawki** [comment] 2017-06-08 18:33
ok, I've had no luck reproducing, closing this and waiting for the inevitable irritation of this hitting somebody again 😭

**Closed by TeoTwawki** 2017-06-08 18:33 UTC
Labels: Escalation Needed / Has been Escalated, ¯\_(ツ)_/¯
