### ISSUE TITLE
BLUs unable to learn spells

### ISSUE THREAD

**Issue by alannor** [LegionDark/Issues#1082] opened 2016-09-10 06:21 UTC
**Date & Time**: 
10/9/2016 14:19

**FFXI Client Version (use `/ver`)**: 
20160728

**Server's Expected Client Version matches, yes/no? (use `@ecv`)**: 
Yes

**Character Name**: 
Alannor

**Nation**: 
Windurst

**Job(level)/Sub Job(level)**: 
BLU/RDM

**NPC or Monster or item Name**: 
All

**Zone name & Coordinates (use `@where`)**: 
All

**ffxiah.com link (for items issues only)**: 
No

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
Unable to learn BLU magic, not juste but everyone that I've spoken to. Only magic learnable appears to be Pollen and randomly off mobs, e.g. lizard. One instance where a player learnt pollen off another player while fighting goblins.

**Comment by alannor** [comment] 2016-09-10 06:24
Maybe related to Piglorian's one about blue magic tool. Just want to confirm that we should stop trying for now. One player has spent three days killing over 100 of those bug things and unable to learb Delta Strike.

**Comment by TeoTwawki** [comment] 2016-09-10 06:41
its the same issue, almost guaranteed. it'll be fixed really soon

**Comment by R3P0FFXI** [comment] 2016-09-17 22:49
@alannor Can you please test and confirm the issue is resolved with massive update part 2

**Comment by R3P0FFXI** [comment] 2016-09-17 23:01
@alannor issue confirmed resolved by players on the server

**Closed by R3P0FFXI** 2016-09-17 23:01 UTC
Labels: Status: Player Reply Required

**Comment by alannor** [comment] 2016-09-18 19:11
Sorry it took awhile but eventually learned water bomb off frogs in Abs La
