### ISSUE TITLE
T3 Sandy VW Belphoebe causing PoL crash

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#861] opened 2016-04-14 13:36 UTC
**Date & Time**: Thursday April 14th, 2016

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: Blu99/rdm49

**NPC or Monster or item Name**: Belphoebe

**Zone name & Coordinates (use `@where`)**: Jugner (north of outpost)

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: no

**Steps To Reproduce / any other info**: Was in a party of 6.  4 people's POL froze when Winter Breeze was cast, even though paralyze proced on Belphoebe, it still froze PoL for us.

**Comment by Samikana** [comment] 2016-04-14 14:29
Hmmm, there was about 10 people (dual boxes included in that count) that was present during a Belphoebe fight last night, 3 of which were Teo, R3, and me.  There is were no crashes. 

@TeoTwawki thought for food?  It used winter breeze a few times yesterday but crashes like that generally are not consistent everytime the tp is used AFAIK.

**Comment by w3genesis** [comment] 2016-04-19 14:21
It might be a problem with all pixie mobs. Was fighting Carabosse, had 4-8 pol crashes per fight.
Also had crash fighting Baba Yaga, and 2 crashes when fighting the normal pixie mobs around the area. 
No specific move set seems to be the trigger for pol crash, seems to happen at random when fighting pixie mob. Kill it fast enough and you get less crash happening.
No crash moving around or fighting non-pixie mobs in area.

**Comment by TeoTwawki** [comment] 2016-04-19 16:09
I fought bel, carabosse, baba yaga, and several other pixies for hours, made sure they used all available tp skills..not once did they crash me. When a mobs tp skill is broken it will crash every time, not just randomly one time for some people and not others. Something else going on, and I've no idea what yet.

And its pretty much never the skill you guys think it is even when one does crash.

**Comment by Samikana** [comment] 2016-04-19 16:28
Could it be like the abyssea crashes?  They were never consistent to one
thing.

**Comment by TeoTwawki** [comment] 2016-04-19 16:33
There are hundreds of other possibilities. All I can say is right now a mobs tp skill didn't do it, and that yes Abyssea area's have a lot of random crashes. But they reported a mob not in Abyssea, so I don't think it was one of those.

**Comment by Samikana** [comment] 2016-04-19 16:33
Oh well I meant similar.  The packet crashes on random mobs.  I feel u

**Comment by benfolka** [comment] 2016-04-24 09:26
the reason it is not crashing you might be your GM armor since it resists everything

**Comment by TeoTwawki** [comment] 2016-04-24 09:27
...That's not how any of this works. Please stop conjecturing.

**Comment by TeoTwawki** [comment] 2016-04-26 01:10
Determined to have most likely been caused by a player action that will be fixed in next maint.

**Closed by TeoTwawki** 2016-04-26 01:10 UTC

**Comment by Samikana** [comment] 2016-04-26 11:29
LMAO I JUST SAW HIS COMMENT WTF LOL I DIDN'T HAVE MY GM GEAR ON.

**Comment by Samikana** [comment] 2016-04-26 11:30
Didn't mean to have caps on.   ^

**Comment by TeoTwawki** [comment] 2016-04-26 17:45
@samikana edit button :wink:
