### ISSUE TITLE
Cavernous Maw Teleport NPC (Port Jeuno)

### ISSUE THREAD

**Issue by Arrytha** [LegionDark/Issues#625] opened 2016-02-21 15:04 UTC
Date & Time: The past week tried it 2-3 times
Frequency: 2-3
FFXI Client Version: 30151223_0
Character Name: Arrytha
Race: Mithra
Nation: San d'Oria
Main Job: THF
Sub Job: DNC
Area & Coordinates: Port Jeuno > Aby - Altepe, Port Jeuno > Aby - Grauberg
Party or Solo: Party
NPC or Monster Name: Horst
ffxiah.com link (for inventory items only): N/A
Multi-boxing? (multiple clients on same connection): No
Steps To Reproduce The Issue: Tried porting with this NPC to either of those two Cavernous Maws for Abyssea with cruor and it makes the animation of warping me there but then my character turns invisible and I can still walk around in Jeuno. The warp bugs out or something and does not port me to the maw. Seems to be working for other people.

**Comment by TeoTwawki** [comment] 2016-02-21 18:39
This comes up now and then, and I've never been able to reliably reproduce it or find a probable cause before it just up and goes away without my intervention. :confused:

**Comment by TeoTwawki** [comment] 2016-02-21 18:41
@Arrytha  double check that you have the required cruor etc. I believe there may be a bug where the NPC tries to go through the motions even when you aren't eligible for teleports

**Comment by Arrytha** [comment] 2016-02-21 22:20
The only thing I can think of that may be a cause of the bug is that I had
not been to either one of the those Cavernous Maws manually in their
respective zones. Now that I have been through them in the actual zone,
maybe that "unlocks" the teleport through the NPC. I will have to do
further testing when I get on this evening. Cruor is confirmed. I have over
200k cruor from leveling in Aby - Attohwa.  Could it possibly be that there
is a quest prerequisite you must complete to "unlock" Abyssea stuff, even
though you can enter the Maws at level 30+?

On Sun, Feb 21, 2016 at 1:41 PM, TeoTwawki <notifications@github.com> wrote:

> @Arrytha <https://github.com/Arrytha> double check that you have the
> required cruor etc. I believe there may be a bug where the NPC tries to go
> through the motions even when you aren't eligible for teleports
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LegionDark/Issues/issues/625#issuecomment-186883285>.
>



-- 
Joe Driver
Survey Party Chief
Terra Engineering and Land Solutions, PC
540-337-4591
http://www.terraengineering.net/

**Comment by Arrytha** [comment] 2016-02-21 22:28
Just tried to port again to a Maw I have been through already and the same
outcome occured: warp animation from Horst, failing to teleport, then my
character turns invisible and can walk around again.

On Sun, Feb 21, 2016 at 5:20 PM, Joe Driver <jdandrive@gmail.com> wrote:

> The only thing I can think of that may be a cause of the bug is that I had
> not been to either one of the those Cavernous Maws manually in their
> respective zones. Now that I have been through them in the actual zone,
> maybe that "unlocks" the teleport through the NPC. I will have to do
> further testing when I get on this evening. Cruor is confirmed. I have over
> 200k cruor from leveling in Aby - Attohwa.  Could it possibly be that there
> is a quest prerequisite you must complete to "unlock" Abyssea stuff, even
> though you can enter the Maws at level 30+?
>
> On Sun, Feb 21, 2016 at 1:41 PM, TeoTwawki <notifications@github.com>
> wrote:
>
>> @Arrytha <https://github.com/Arrytha> double check that you have the
>> required cruor etc. I believe there may be a bug where the NPC tries to go
>> through the motions even when you aren't eligible for teleports
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/LegionDark/Issues/issues/625#issuecomment-186883285>.
>>
>
>
>
> --
> Joe Driver
> Survey Party Chief
> Terra Engineering and Land Solutions, PC
> 540-337-4591
> http://www.terraengineering.net/
>



-- 
Joe Driver
Survey Party Chief
Terra Engineering and Land Solutions, PC
540-337-4591
http://www.terraengineering.net/

**Comment by Baucant** [comment] 2016-02-21 23:27
did you do the quest with Jochim first...you have to zone to PJ get CS, Talk to Joachim get CS and KI, go to an abby zone... get CS, go back to Joachim and get another CS then you should be able to tele to all zones. Aleast that how my new Alt just did it less then a week ago.

**Comment by TeoTwawki** [comment] 2016-02-22 00:19
If Horst is trying to do the port before the part with Joachim has ever been done, I think that still leaves me something to fix if confirmed. 

I just have to find out what exactly the circumstances are behind this weirdness in order to fix whatever it is.

**Comment by Arrytha** [comment] 2016-02-22 00:31
Baucant, I did not do all those steps I have the Traverser's Stone KI but I
don't recall getting a CS in an Aby zone. I talked to Joachim for CS then
to Horst in that order, yes. Horst wouldn't talk to me before Joachim. I
will try zoning into an Aby solo and see if I can trigger a CS.

On Sun, Feb 21, 2016 at 7:19 PM, TeoTwawki <notifications@github.com> wrote:

> If Horst is trying to do the port before the part with Joachim has ever
> been done, I think that still leaves me something to fix if confirmed.
>
> I just have to find out what exactly the circumstances are behind this
> weirdness in order to fix whatever it is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LegionDark/Issues/issues/625#issuecomment-186949424>.
>



-- 
Joe Driver
Survey Party Chief
Terra Engineering and Land Solutions, PC
540-337-4591
http://www.terraengineering.net/

**Comment by TeoTwawki** [comment] 2016-02-22 00:37
There should be a CS in Jeuno that sets off the overall quest line, then each maw has its own associated quest related to its boss. perhaps the unlock conditions for the teleports are missing/wrong. Its been so long I don't remember how much of Horst is coded only remember running a character through and teleportings working correctly for me.

**Comment by TeoTwawki** [comment] 2016-02-22 00:38
Due to other higher priorities, it may be awhile before I can recode Horst. Anything wrong here is going to be wrong in darkstar as well.

**Comment by Arrytha** [comment] 2016-02-22 00:41
I've done near zero missions beyond Chains of Promathia so that is likely a
contributor to my issue. No worries on a fix soon, I just wanted to report
a bug in case it hadn't been a known issue yet. :)

On Sun, Feb 21, 2016 at 7:38 PM, TeoTwawki <notifications@github.com> wrote:

> Due to other higher priorities, it may be awhile before I can recode
> Horst. Anything wrong here is going to be wrong in darkstar as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LegionDark/Issues/issues/625#issuecomment-186952829>.
>



-- 
Joe Driver
Survey Party Chief
Terra Engineering and Land Solutions, PC
540-337-4591
http://www.terraengineering.net/

**Comment by Arrytha** [comment] 2016-02-22 00:57
If it is indeed a bug and not just on my end. Will keep updates if I get it
fixed

On Sun, Feb 21, 2016 at 7:41 PM, Joe Driver <jdandrive@gmail.com> wrote:

> I've done near zero missions beyond Chains of Promathia so that is likely
> a contributor to my issue. No worries on a fix soon, I just wanted to
> report a bug in case it hadn't been a known issue yet. :)
>
> On Sun, Feb 21, 2016 at 7:38 PM, TeoTwawki <notifications@github.com>
> wrote:
>
>> Due to other higher priorities, it may be awhile before I can recode
>> Horst. Anything wrong here is going to be wrong in darkstar as well.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/LegionDark/Issues/issues/625#issuecomment-186952829>.
>>
>
>
>
> --
> Joe Driver
> Survey Party Chief
> Terra Engineering and Land Solutions, PC
> 540-337-4591
> http://www.terraengineering.net/
>



-- 
Joe Driver
Survey Party Chief
Terra Engineering and Land Solutions, PC
540-337-4591
http://www.terraengineering.net/

**Comment by TeoTwawki** [comment] 2016-02-22 00:59
I appreciate the time testing it for me, I have had my hands so full.

**Comment by PikaFox** [comment] 2016-02-22 01:04
Iirc this happened to me as well when i started, and it was because i didnt do all the retail required prerequisites.

Get CS in port jeuno, talk to Jochim, go to an abyssea maw and enter, return to Jochim and request another traverser stone. This should allow you to warp to any maw that you have visited (not sure if you need to visit them again or at all technically), assuming i remembered everything right.

**Comment by PikaFox** [comment] 2016-02-22 01:07
Will only give you the option to teleport to a maw if you have watched the cutscene triggered on examining it for the first time. Note that you must talk to Joachim after receiving the cutscene at your first Scars of Abyssea maw to receive cutscenes from examining the other maws; you will simply be allowed into the other zones without a cutscene nor teleport access from Horst. You must also be in possession of at least one Traverser Stone to receive a cutscene at its corresponding Cavernous Maw.

- http://ffxiclopedia.wikia.com/wiki/Horst

**Comment by Samikana** [comment] 2016-02-25 20:17
@PikaFox when you enter the maw, you have to talk to the conflux surveyor or you won't get access to fix the quest.  The NPC wont give any dialogue, but it'll update your mission log.

I'm closing this.  The player hasnt responded in more than 3 days so I'm going to assume that their issue is fixed.

**Closed by Samikana** 2016-02-25 20:17 UTC

**Comment by Arrytha** [comment] 2016-02-25 20:23
I apologize, I haven't had time to further test the issue yet but upon
entering an abyssea zone I noticed the conflux surveyor was asking for
traverser stones so I will try Sami's info and see if that gives me tele
access via Horst.

Thanks!
Arrytha

On Thu, Feb 25, 2016 at 3:17 PM, Sami <notifications@github.com> wrote:

> @PikaFox <https://github.com/PikaFox> when you enter the maw, you have to
> talk to the conflux surveyor or you won't get access to fix the quest. The
> NPC wont give any dialogue, but it'll update your mission log.
>
> I'm closing this. The player hasnt responded in more than 3 days so I'm
> going to assume that their issue is fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LegionDark/Issues/issues/625#issuecomment-188960981>.
>



-- 
Joe Driver
Survey Party Chief
Terra Engineering and Land Solutions, PC
540-337-4591
http://www.terraengineering.net/
