### ISSUE TITLE
Zero damage weapon skills.

### ISSUE THREAD

**Issue by JessLand86** [LegionDark/Issues#1166] opened 2016-10-14 01:31 UTC
**Date & Time**: 
10/13/2016 9:19 est

**FFXI Client Version (use `/ver`)**: 
60831_1
**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
Yes

**Character Name**: 
Immortality

**Nation**: 
Sandy

**Job(level)/Sub Job(level)**: 
99THF/49DNC

**NPC or Monster or item Name**: 
Various

**Zone name**: 
Several

**Coordinates (use `$where`)**: 
Various

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 
Yes

**Steps To Reproduce / any other info**: 
When using weapon skills, you will occasionally hit for 0 points. I was able to reproduce on several different mobs using Rudra's storm, others have mentioned it with different weapon skills. None of the mobs that I  fought had stoneskin or other damage nullifying buffs on. I attached some of the 0 WS's I remembered to get a screenshot of. 

![immortality_2016 10 13_013942](https://cloud.githubusercontent.com/assets/22607214/19372618/a00263ea-918b-11e6-9894-58bcc082cba1.png)
![immortality_2016 10 13_014251](https://cloud.githubusercontent.com/assets/22607214/19372620/a0047f40-918b-11e6-8af1-ce9e6abe4cad.png)
![immortality_2016 10 13_055548](https://cloud.githubusercontent.com/assets/22607214/19372619/a003258c-918b-11e6-9acf-7e4f8b5bbbb5.png)

**Comment by PikaFox** [comment] 2016-10-14 01:32
https://github.com/LegionDark/Issues/issues/1161

So it seems the issue is still happening.

**Comment by TeoTwawki** [comment] 2016-10-14 01:35
:cry: :scream:

**Comment by JessLand86** [comment] 2016-10-14 01:42
I fell asleep before submitting this last night, I didn't see Pika's ticket, if it's fixed then I apologize for submitting a duplicate. I thought I searched for open and closed tickets that would already cover this, but apparently I missed it.

**Comment by TeoTwawki** [comment] 2016-10-14 01:43
well if it hasn't happened to you since I closed the other one, then it should be fixed. if it has happened since. Then I need to know.

**Comment by JessLand86** [comment] 2016-10-14 02:49
Still borked. Just did another 0 Rudra's.
![immortality_2016 10 13_224831](https://cloud.githubusercontent.com/assets/22607214/19374096/5971b4c4-9197-11e6-9351-396d9d072c48.png)

**Comment by TeoTwawki** [comment] 2016-10-14 03:11
Curses.

**Comment by TeoTwawki** [comment] 2016-10-14 06:02
Spent a few hrs trying and failing to determine the root cause. There is an open issue in Darkstars tracker for it right now.

**Comment by TeoTwawki** [comment] 2016-10-14 06:03
Seems possible to happen randomly on *any* weaponskill.

**Comment by TeoTwawki** [comment] 2016-10-29 02:23
There has a been a code change, and I now need a fresh post update screencap of this happening. showing it on a single hit ws would be ideals but I'll take any proof at all of it still happening.

**Comment by JessLand86** [comment] 2016-10-29 10:10
I'll keep my eyes open to see if it's still happening.

**Comment by R3P0FFXI** [comment] 2017-01-11 03:02
@TeoTwawki @JessLand86 is this still an issue or has DSP resolved this?

**Comment by TeoTwawki** [comment] 2017-01-11 03:04
was still a thing after their "fix" and I haven't heard more sicne, nor has any new fix happened

**Comment by JessLand86** [comment] 2017-01-14 01:59
I haven't managed to recreate it anymore, if it still is a bug then it's a lot less prevalent. I've had some stupid low number (30-90) weapon skills, but none for zero in a long time.

**Comment by TeoTwawki** [comment] 2017-04-19 23:41
if anyone ever manages to get me proof of it happening again, please make a new issue for it.

**Closed by TeoTwawki** 2017-04-19 23:41 UTC
Labels: DSP problem: Not our bug / Not Implemented
