### ISSUE TITLE
Jishnu's Radiance only 1 hit 

### ISSUE THREAD

**Issue by nemesisx101** [LegionDark/Issues#385] opened 2015-10-18 16:34 UTC
**Date & Time**: October 18, 2015
**Frequency**: Every time I use the Weapon Skill
**FFXI Client Version**:30150730_1
**Character Name**:Nemesisx
**Race**:Hume
**Nation**:Bastok
**Main Job**:Ranger
**Sub Job**:Warrior
**Area & Coordinates**:X:0 Y:0 Z:-2(199)
**Party or Solo**:Solo
**NPC or Monster Name**:NA
**ffxiah.com link (for inventory items only)**: NA
**Multi-boxing? (multiple clients on same connection)**:NO
**Steps To Reproduce The Issue**: Tried different Mobs different areas other Rangers claim same issue

**Comment by TeoTwawki** [comment] 2015-10-18 16:37
Def not one hit. I looked at the code, its set to 4 hits. You may be missing 3 of them. The ws itself may have an acc problem, if you are missing 3 of 4 of its hits vs lv 0 bunny in west ron. for example, or your target may have too high an evasion stat.

**Comment by TeoTwawki** [comment] 2015-10-18 16:39
@Loki79 you modded this and I know you did testing before, if you say Its workin *as intended* I dang well believe it.

**Comment by Loki79** [comment] 2015-10-18 22:03
This WS has been buffed well beyond what it should be already and performs quite nicely.  Closing this.

**Closed by Loki79** 2015-10-18 22:03 UTC

**Comment by TeoTwawki** [comment] 2015-10-18 22:06
@nemesisx101 @Loki79 someone on IRC mentioned it not deducting multiple arrows from inventory, and I just wanted to mention thats not a reliable indicator of hits landed, both because of  recycle and the likelihood that DSP doesn't even have code to remove multiple arrows on a ranged ws.
