### ISSUE TITLE
~ Jailer of Love adds ~

### ISSUE THREAD

**Issue by simthra** [LegionDark/Issues#1148] opened 2016-10-08 06:01 UTC
**Date & Time**: 7 oct 2016, 00.00 GMT+1

**FFXI Client Version (use `/ver`)**: 30160831_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**:  yes

**Character Name**: Thranduil

**Nation**: Bastok

**Job(level)/Sub Job(level)**: BLU99/RDM49

**NPC or Monster or item Name**: Jailer of Love

**Zone name**: Al'Taieu

**Coordinates (use `$where`)**: 437.76, Y: -1.643, Z: -598.571 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**:  yes

**Steps To Reproduce / any other info**: JoL seconds before being defeated spawned his wave of 3 RuPhuabo helpers; these phuabos have no name upon them, are un-targettable and invicible. We'couldn't kill them, so no AV, darn.

**Comment by TeoTwawki** [comment] 2016-10-08 06:10
Good news: they aren't related to the AV popping or not, if JoL dies those dice roll, even if the adds are still up or in this case, bugged and stuck. So you didn't miss out on AV from them being bugged. 

I'll look into finding a way to prevent them getting stuck. I know the cause but its a DSP bug thats not likely to get fixed anytime soon. Hopefully I can find a way to avoid tripping it instead.

**Comment by TeoTwawki** [comment] 2016-10-08 06:50
On further investigation, those phuabo didn't trip the bug I thought they did, it may take awhile to fix them but on the bright side it won't randomly happen again once I track down the problem..

**Comment by simthra** [comment] 2016-10-08 09:38
All right, so AV won't pop 100% from JoL. Thanks.

**Comment by TeoTwawki** [comment] 2016-10-08 09:39
Yeah he's a random chance.

**Comment by TeoTwawki** [comment] 2016-10-08 10:15
Hey how bout that, its a DSP thing afterall.. https://github.com/DarkstarProject/darkstar/pull/3420
Will be all fixed once thats merged and legion updates again.

**Comment by R3P0FFXI** [comment] 2016-10-09 02:36
@TeoTwawki @simthra DSP merged requests this should be apart of next maint

**Comment by R3P0FFXI** [comment] 2016-10-12 02:03
Issue resolved in todays maint

**Closed by R3P0FFXI** 2016-10-12 02:03 UTC
