### ISSUE TITLE
Additional effect 161383 points of damage?

### ISSUE THREAD

**Issue by SledgeCalamy** [LegionDark/Issues#1400] opened 2017-03-09 21:30 UTC
**Date & Time**: 
09/03/17

**FFXI Client Version (use `/ver`)**: 
30170204_1

**Server's Expected Client Version matches, yes/no? (use `$ecv`)**: 
yes

**Character Name**: 
Sledge

**Nation**: 

**Job(level)/Sub Job(level)**: 

**NPC or Monster or item Name**: 
Tegmine

**Zone name**: 
Cape Terrigan

**Coordinates (use `$where`)**: 

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: 

**Steps To Reproduce / any other info**: 
Chat scripts Tegmine doing over 100k damage on additionnal effect however it's probably 2-3 damage per effect, not an issue for killing the nm,  just noting as a chat glitch

**Comment by R3P0FFXI** [comment] 2017-03-10 02:13
Escalating to @TeoTwawki possible buffer over/underrun on additional effects

**Comment by spectre99** [comment] 2017-03-10 11:40
Just wanted to add that I was doing Jorm earlier and every so often he'd also do additional effect damage that was 131k+.  So whatever it is seems to be affecting more than just Tegmine.

**Comment by spectre99** [comment] 2017-03-10 11:51
Just a quick ps.  It doesn't actually do that much damage, but the chat log shows it as damage taken.  Here's a screenshot.

http://imgur.com/3604467e-4537-4b53-bc33-719fdc0cc385

**Comment by SledgeCalamy** [comment] 2017-03-10 11:59
I think the issue is there is missing a coma, chat wirtting 161383 instead of 16.1383 damage

**Comment by R3P0FFXI** [comment] 2017-03-10 22:40
This has been confirmed by @TeoTwawki that it is an issue, it has nothing do with Commas or anything like that he will work on removing the code it may take some time.

**Comment by TeoTwawki** [comment] 2017-03-29 23:50
improper handling of an integer that gets checked for various things - like when one of those "absorbs <\element\>" things procs and it's supposed to heal you instead of hurt you.

**Comment by R3P0FFXI** [comment] 2017-05-12 00:16
issue resolved in todays update

**Closed by R3P0FFXI** 2017-05-12 00:16 UTC
Labels: Status: will be taken care of in future maintenance/update
