### ISSUE TITLE
The (at)stats GM command is "derpy and unreliable" (Teo's words)

### ISSUE THREAD

**Issue by Genesis-Legion** [LegionDark/Issues#60] opened 2015-06-04 23:10 UTC
Date & Time: 6/4/15
Frequency: Always
FFXI Client Version: 30150508_8
Character Name: Genesis
Race: Hume
Main Job: SAM
Sub Job: Any
Area & Coordinates: Anywhere
Party or Solo: Any
NPC Name: NA
Monster Name: NA

Using ```@stats``` is showing that with a Hangaku-no-yumi(119 bow) is only raising my accuracy +15 (the bow has +15 r.acc on it) being equpped coming out to a total of 486 ranged accuracy, ranged accuracy only drops 15 (the +15 on the bow) when I unequip it, compared to the melee accuracy of 828 with a 119 gkt (Tsurumaru working normally) equipped, melee accuracy drops to 258 with nothing equipped.

**Comment by itachioax** [comment] 2015-06-05 04:49
perhaps cuz u have 2 119 weapons

**Comment by Loki79** [comment] 2015-06-05 16:28
@TeoTwawki i have looked at this and cant find anything wrong.  I think the issue may be with the "stats" cmd itself.  I'm told the commit from KJ is handling the +skill for Ranged weapons and the packet sends the info correctly.  At this point im out of ideas....

**Comment by Loki79** [comment] 2015-06-05 23:55
closing this out.  The gear works as intended the cmd doesnt.  My vote would be to nuke the cmd but seems ppl like it.  to see that it applies use /checkparam <me>, that show the RATT and RACC applied correctly.

**Comment by TeoTwawki** [comment] 2015-06-06 02:44
Almost derped up them labels mixing up @stats and /checkparam in my head. I'll see if I can clean up the garbage bits of ```@stats```...Going to remove anything shown by ```/checkparam``` and anything that cannot be accurately measured and displayed while fixing what I can.

**Comment by TeoTwawki** [comment] 2015-06-06 02:48
My apologies to the user named **stats**, lol

**Comment by Genesis-Legion** [comment] 2015-06-06 02:56
Ah that was my derp then, hardly ever used /checkparam and I can see that it does indeed show the correct ranged accuracy, sorry for the trouble lol

**Comment by TeoTwawki** [comment] 2015-06-09 10:51
Adjusted the ```@stats``` GM command. Should no longer display batshit insane values once the next maintenance finished.

**Closed by TeoTwawki** 2015-06-09 10:51 UTC
Labels: Status: Investigation / Work In Progress
