### ISSUE TITLE
Random client crashes that happen in Abyssea

### ISSUE THREAD

**Issue by Squall-Bibi** [LegionDark/Issues#85] opened 2015-06-11 19:21 UTC
**Date & Time**: 11/06/2015
**Frequency**: always
**FFXI Client Version**: 30150508_5
Revision : a137e3f0075cce9336bc5b929829ace9acf0c58c
**Character Name**: Squall but all ppl
**Race**: Hume but all
**Main Job**:  BLU but all ppl
**Sub Job**: NIN but all ppl 
**Area & Coordinates**: Abyssea - Attohwa
**Party or Solo**: alone and party same
**NPC Name**:
**Monster Name**:
**Steps To Reproduce The Issue**:

inside Abyssea - Attohwa randomly crash, very very very often, in 1H  today i crash 10 - 20 times ....
Yesterday less crash but is completly random.

**Comment by atom0s** [comment] 2015-06-11 19:54
Incomplete template. Closing.

**Comment by Squall-Bibi** [comment] 2015-06-12 05:46
what ? template is copy paste !

**Comment by atom0s** [comment] 2015-06-12 05:55
You, like a lot of people, did not include your FFXi client version. Which is required for reports posted here.

**Comment by Squall-Bibi** [comment] 2015-06-12 05:57
lol ok is misstake is ok, my revision is very long now ! is normaly ? i repost my revision here or create new ticket ?

**Comment by atom0s** [comment] 2015-06-12 05:57
You can update the ticket and I can reopen it if you include the required info.

**Comment by Squall-Bibi** [comment] 2015-06-12 06:01
FFXI Client Version : 30150508_5
@Revision : a137e3f0075cce9336bc5b929829ace9acf0c58c

**Comment by SomeGlenn** [comment] 2015-06-12 11:48
Adding a little more detail. My client's 30150508_8
I've noticed that I randomly get a POL crash when the mob does a flame breath. Sometimes it does, sometimes it doesn't. When it does, the last thing to appear on my battle log is always "XXX uses Flame Breath".

Always happens when farming Blazing Eruca. The zone itself is fine. I've merited there for hours, killed Ulhadashi, Warbler, and no issues at all. Just that crawler.

**Comment by Loki79** [comment] 2015-06-12 13:39
if it was a bad skill script it would crash the server.  Wondering if we have text ID issues there?  can you think of any other reason it would only kill client?  @atom0s @TeoTwawki

**Comment by TeoTwawki** [comment] 2015-06-12 15:08
@Loki79 have to test the message ID and animation ID to find out if that's triggering it.

**Comment by TeoTwawki** [comment] 2015-06-12 21:55
The msg ID was wrong, but was not crashing. Animation didn't crash either. I fed the mob TP and got them to use the move more than a dozen times, not one crash form it. Whatever the crash is form, this ain't it.

**Comment by Baucant** [comment] 2015-06-12 23:19
I too Have experiance this client crash, I noticed that usally It would be one toon or the other.I thought possible the issue was on my end but bit now that I see others are having the same issue I thought I would share my experiances. on sunday me and about 8 other went there after our failed attempt to aquire atma of Razed Ruin. before we could even beging farming pop items people started crashing 3-5 at a time. even when we not fighting anything. I came back after maintance again hoping to fight Blazing Eruca. fought him numberous times and one of my toon would crash every time while fighting him i can't confirm that it was always doing flaming breath as I recall once it was cast one of the AM spells (quake, freeze, flood, flare ect)

**Comment by Squall-Bibi** [comment] 2015-06-13 06:51
i say it completely random for me not just flame breath, need to review all spells crawler i think no just one.

**Comment by R3P0FFXI** [comment] 2015-06-13 14:24
Opened DSP bug for this issue

https://github.com/DarkstarProject/darkstar/issues/1588

**Comment by TeoTwawki** [comment] 2015-06-13 14:25
I got a crash to happen but it was just by standing in that area...without any action happening. WTF,

**Comment by TeoTwawki** [comment] 2015-06-13 17:59
Seems to just be a random occurrence on:
* moving away form a mob as it is in its death animation
* killing multiple mobs very quickly
* fighting mobs at specific spots, like the NM pop site.
For no damn reason I can see.

I was able to kill 40 crawler with no problem at all, 1 at a time, after pulling them up by the rock Murex. Second I walked away form one as its falling down, crashed.

**Comment by Loki79** [comment] 2015-07-17 02:16
This still going on?  havent heard about it lately?  tagging with waiting, if nothing in 5 days closing.

**Comment by TeoTwawki** [comment] 2015-07-21 19:10
I missed this. pretty much gonna be an issue till someone in DSP gives a f*** about it. Reopening just to act as duplicate issue prevention measure.

**Comment by atom0s** [comment] 2015-07-21 22:55
Given that this seems to happen the most in zones that DSP does not support, don't expect them to care anytime soon.

**Comment by TeoTwawki** [comment] 2015-07-25 21:41
> R3P0FFXI changed the title from Abyssea - Attohwa [randomly crash game for all ppl] to Mules on Seperate servers randomly cause crashing when zoning from 1 ZMQ to another 8 hours ago

@R3P0FFXI wtf these are not even remotely similar!

**Comment by goferffxi** [comment] 2015-08-15 16:57
If I may add to this, I have experienced 2 POL crashes using ashita in Aby- Konschtat while fighting raskovnik. After first crash moved to a diff location and still got a crash. Ill add the template below

Date & Time: 15/06/2015
Frequency: always
FFXI Client Version: 30150508_5
Character Name: Gofer
Race: Taru
Main Job: NIN
Sub Job: WAR
Area & Coordinates: Abyssea Konschtat
Party or Solo: duo
NPC Name: 
Monster Name: Rasknovic
Steps To Reproduce The Issue:.
Rasknovic battle commences and fight until crash occours.

**Comment by atom0s** [comment] 2015-08-16 00:34
Still falls under the same issues as before, there are a lot of issues with Abyssea zones due to how entity packets are handled in DSP. This is something that is unlikely to be fixed anytime soon as well given that DSP does not support any Abyssea content yet.

**Comment by R3P0FFXI** [comment] 2016-03-16 17:38
Reopen if still an issue after update

**Closed by R3P0FFXI** 2016-03-16 17:38 UTC
Labels: DSP problem: Not our bug / Not Implemented

**Comment by TeoTwawki** [comment] 2016-03-16 21:27
Should be 90% fixed post update. Issues may still persist in Abyssea Attohwa (I'm fairly sure its related to the missing gas wall objects)
