### ISSUE TITLE
 Spool Of Ruby Silk Thread ,does not exist in the server

### ISSUE THREAD

**Issue by nekrol** [LegionDark/Issues#301] opened 2015-09-09 20:17 UTC
Date & Time: 09/09/2015, 08:00am
Frequency: Always
FFXI Client Version: 30150730_2
Character Name: Myeva
Race: Hume
Main Job: Rdm
Sub Job: Whm
Area & Coordinates: none
Party or Solo: Party or solo
NPC Name: 
Monster Name: Irrelevant
Multi-boxing? (multiple clients on same connection): no
Steps To Reproduce The Issue  Spool Of Ruby Silk Thread ,does not exist in the server ,

**Comment by TeoTwawki** [comment] 2015-09-09 20:22
Existing and dropping are not same thing. Very definitely exists, and should be a possible reward item in limbus. We'll have to double check if it is attainable and get back to you.

**Comment by TeoTwawki** [comment] 2015-09-09 20:23
Please note the template has been updated to include things you did not, in the future staff will be insisting on item reports having their item link.

**Comment by TeoTwawki** [comment] 2015-09-09 21:58
Confirmed this and a dozen others were not dropping...

I have written a workaround, any and all mobs in all limbus zones should now have a chance to drop an additional item, which can be any and all possible materials so no job gets left out. This should be live and working without restarting the server shortly, just need some testing to confirm my fix works as intended.

**Comment by nekrol** [comment] 2015-09-09 22:58
thanks you

**Comment by nekrol** [comment] 2015-09-10 01:56
after 3 weeks and still nothing will every day limbus is unfair and not drop the item

**Comment by nekrol** [comment] 2015-09-10 02:01
is unfair not to give me Voidstone, Aurel and my cassy char vidtone more reciven not more than one month, more nesesitan and go in the folder 3 and I do not leave the 1 causes

**Comment by TeoTwawki** [comment] 2015-09-10 02:02
DO NOT WHINE AT ME

**Closed by TeoTwawki** 2015-09-10 02:02 UTC

**Comment by TeoTwawki** [comment] 2015-09-10 02:04
I was working on the issue, and you turned this bug report into complaining about fairness. Do I have a big red and yellow S on my chest? Do I look like superman to you? Paid tech support for pay to play games do not have this fast of a turn around time on their tickets, why the hell to people think its acceptable to act like this with a game that is entirely free run by people who do this as a hobby?

**Comment by R3P0FFXI** [comment] 2015-09-10 03:39
after 3 weeks huh funny this was opened 7 hours ago and already someone had been working on it. Now screw it well fix it when we do.

**Comment by TeoTwawki** [comment] 2015-09-10 04:12
And only a few hours after I said I had a fix coming and just needed to test it. And he's bringing up unrelated issues here.

**Comment by TeoTwawki** [comment] 2015-09-10 05:56
My fix is now live on the server and works. Posting an announcement about it to the forums.
