### ISSUE TITLE
Relic Trial problems =(

### ISSUE THREAD

**Issue by itachioax** [LegionDark/Issues#509] opened 2016-01-16 16:26 UTC
**Date & Time**: 
**Frequency**:
**FFXI Client Version**:
**Character Name**: Itachioax
**Race**: Hume
**Nation**: Sandy
**Main Job**: MNK
**Sub Job**: DNC
**Area & Coordinates**:
**Party or Solo**: SOLO
**NPC or Monster Name**: Adamantoise
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? sometimes
**Steps To Reproduce The Issue**:
im doing second relic trial, faffy and behe works ok, but already killed 4 adamantoise and doesnt count in my trial, i took some pictures, not all them just 2 kills of it

First time
![img_20160115_235244](https://cloud.githubusercontent.com/assets/12620527/12373317/189f41b4-bc3b-11e5-8e54-3592903ee777.png)
![img_20160115_235253](https://cloud.githubusercontent.com/assets/12620527/12373318/18a5a1bc-bc3b-11e5-8506-b1bbacecf95b.png)

Second time
![img_20160116_100639](https://cloud.githubusercontent.com/assets/12620527/12373323/51231830-bc3b-11e5-98e5-d7c47b5fd3e0.png)
![img_20160116_101531](https://cloud.githubusercontent.com/assets/12620527/12373324/5126a568-bc3b-11e5-876b-11ad0dc4634f.png)
check how behe works ok
![img_20160116_102151](https://cloud.githubusercontent.com/assets/12620527/12373327/6a089000-bc3b-11e5-8c6f-431691d4c6ea.png)

so, should i take picture every kill or what i should to do ??

**Comment by Samikana** [comment] 2016-01-16 16:37
@itachioax @Nemesisx @trueamer @Genesius1490 all of you need to contact me in-game

**Comment by itachioax** [comment] 2016-01-16 18:08
i dont understand thye know how ???

**Comment by Samikana** [comment] 2016-01-17 02:03
you need to contact ME

**Comment by Samikana** [comment] 2016-01-17 17:21
I told @itachioax to post a SS everytime he kills Adamantoise

**Comment by thiefx** [comment] 2016-01-18 08:21
I just had the exact same issue happen. Killed Adamantoise, no count towards Excalibur trial.

Date & Time: Jan 18th, 11:00pm
Frequency: First time
FFXI Client Version: 30151215_0
Character Name: Uubu
Race: Mithra
Nation: Bastok
Main Job: PLD
Sub Job: DNC
Area & Coordinates: Valley of Sorrows
Party or Solo: SOLO
NPC or Monster Name: Adamantoise
ffxiah.com link (for inventory items only): 
Multi-boxing? nope
**Steps To Reproduce The Issue:
Killed Adamantoise solo, took about 20 minutes as crappy undergeared PLD. No count towards relic trial.

![capture](https://cloud.githubusercontent.com/assets/1922983/12386303/71012608-bd79-11e5-86d0-694283ad8be8.PNG)
![capture2](https://cloud.githubusercontent.com/assets/1922983/12386304/7101b550-bd79-11e5-962e-3e5df8b7b6c3.PNG)
![capture3](https://cloud.githubusercontent.com/assets/1922983/12386305/71026a0e-bd79-11e5-9841-5d23b5261261.PNG)

**Comment by thiefx** [comment] 2016-01-18 08:22
3rd pic was meant to prove that I had Excalibur on, but I had the cursor on the wrong selection. I had Excalibur equipped for the entire battle.

**Comment by Samikana** [comment] 2016-01-18 17:24
@thiefx please message me (Halsey) in-game next time youre on

**Comment by TeoTwawki** [comment] 2016-01-18 18:53
Fucking addTitle() line was broken in legions script, which halted it so it never reached trial check. is fixed now.

**Comment by TeoTwawki** [comment] 2016-01-18 18:54
Note: this ONLY effected adamantoise. the others were all fixed days ago.

**Comment by Samikana** [comment] 2016-01-18 19:44
@TeoTwawki since the server crashed, should it be in?

**Comment by TeoTwawki** [comment] 2016-01-18 19:45
its in even without a crash or restart

**Closed** 2016-01-18 21:47 UTC
Labels: Status: Investigation / Work In Progress, Status: Player Reply Required, Todo: Trial Bugfix
