### ISSUE TITLE
CoP 4-3 The Secrets of Worship

### ISSUE THREAD

**Issue by adfasdaf** [LegionDark/Issues#382] opened 2015-10-16 21:56 UTC
**Date & Time**: 10-16 430p
**Frequency**:often
**FFXI Client Version**:30150910_3
**Character Name**:Tron and also Synergy
**Race**:elvaan
**Nation**:sandy
**Main Job**:sam
**Sub Job**:war
**Area & Coordinates**:Misareaux Coast
**Party or Solo**:Party
**NPC or Monster Name**:
**ffxiah.com link (for inventory items only)**: 
**Multi-boxing? (multiple clients on same connection)**:No
**Steps To Reproduce The Issue**: After CS with Justinius we headed out to the gate at G4 in Miserable Coast. The cut scene started for both us. However, prishe in the CS to let us through the gate during the cutscene. For some reason she came up as a tarutaru and the cutscene froze mutltiple times for us after she came through the door. The game didn't freeze but the cutscene will not advance past that point. Only thing at that point was to @homepoint or @return as nothing else was working.

**Comment by TeoTwawki** [comment] 2015-10-16 21:59
Caused by client version being newer than server version.

**Comment by TeoTwawki** [comment] 2015-10-16 21:59
Editing that label to not cause confusion about this...

**Comment by adfasdaf** [comment] 2015-10-17 14:53
So we are stuck? Just for clarification.

**Comment by TeoTwawki** [comment] 2015-10-17 15:24
till server gets updated you are boned dude.

**Comment by TeoTwawki** [comment] 2015-10-17 15:25
Am trying to make that happen as fast as possible, but no eta

**Comment by PikaFox** [comment] 2015-10-17 19:16
Some people have had luck getting CS freezing to stop when they ran the "chocobo" fix. If you dont have that yet, you could try using that. If you do, then theres nothing else i can suggest til we update.

**Comment by R3P0FFXI** [comment] 2015-10-21 10:48
Closing as player declared us to mean because they had no clue what dual boxing is and could not comprehend even if on a VPN or Proxy you were still on the same physical IP on his end and did not like the rule no dual boxing Legion, Dynamis and Limbus

**Closed by R3P0FFXI** 2015-10-21 10:48 UTC
Labels: Status: Not a bug / Just version mismatch / Working As Intended
