### ISSUE TITLE
ZM4 Can't Be Completed

### ISSUE THREAD

**Issue by Blackenx** [LegionDark/Issues#16] opened 2015-05-27 08:09 UTC
**Date & Time**: 5/27/15 3:42am EST
**Frequency**: Everytime, so far I tried it 4 times with the same results
**FFXi Client Version**: 30150508_8
**Character Name**: Blacken
**Race**: Hume
**Main Job**:  99 THF
**Sub Job**: DNC
**Area & Coordinates (Type @where to get this info.)**:  x329 y0 z-300 (127) Sacrificial Chamber
**Party or Solo**: Solo
**NPC Name**: 
**Monster Name**:
**Steps To Reproduce The Issue**: Beat the 3 Tonberries.  Grav'iton appears and a cutscene begins. 

Once we get up to quote below in the cutscene it will get stuck the mission can't be completed the screen stays black. At this point I need to @homepoint to unstuck myself but the cutscene doesn't finish nor the  mission doesn't complete in the process.

Quote: The land where the Zilart resided sank to the abyssal depths of the sea, while the overwhelming power of the crystals laid waste to the Northlands, leaving them uninhabitable.

**Comment by R3P0FFXI** [comment] 2015-05-28 00:51
DSP Issue temp fixed player 

@delkeyitem 238
@addkeyitem 246

@completemission 3 8
@addmission 3 10

Issue forwarded to DSP to resolve CS issues on 2nd CS

**Comment by TeoTwawki** [comment] 2015-05-28 00:53
Reference DSP issue: https://github.com/DarkstarProject/darkstar/issues/1425

**Comment by TeoTwawki** [comment] 2015-05-30 20:43
k, Legion has not changed an effing thing here, and I can reproduce the bug exactly as it happens on legion, but I just got the "works for me can't do anything" handwave dismissal from DSP's lead dev because he says this doesn't happen when he tries it. 

All I can do here is disable part of the mission causing you to never see the problem cs in order to get the mission to advance.

**Comment by TeoTwawki** [comment] 2015-06-04 05:22
Fixed by commenting out the offending code.

**Closed by TeoTwawki** 2015-06-04 05:22 UTC
Labels: Status: Investigation / Work In Progress, Status: Not Our Bug
