### ISSUE TITLE
Unable to attain Assimilator's charuqs +1 

### ISSUE THREAD

**Issue by spectre99** [LegionDark/Issues#923] opened 2016-05-01 06:57 UTC
**Date & Time**: 5/1/2016 1:52am

**FFXI Client Version (use `/ver`)**: 30160329_1

**Character Name**: Spectre

**Nation**: Windurst

**Job(level)/Sub Job(level)**: blu99/rdm49

**NPC or Monster or item Name**: Renik

**Zone name & Coordinates (use `@where`)**: Upper Jeuno X:-15 y:0 Z:36 (215)

**ffxiah.com link (for items issues only)**: na

**Multi-boxing? (multiple clients on same connection)**: na

**Steps To Reproduce / any other info**: I reforged my Af1 using apants, then went to Renik to upgrade it to Assimilator's charuqs +1 using Rem chapter 1.  When I traded instead of getting my blu af1 reforge I got Convoker's pigaches +1, which is the summoner reforge+1.  Luckily I had turned in the apants and tried to upgrade to +1 back to back, so I have a screenshot showing me getting Assimilator's charuqs, then getting a Convoker's pigaches +1.  This is almost 3 weeks worth of work, collecting items to upgrade af, then collecting apants, THEN collecting the rem chapters.

(oops, forgot screenshot http://i.imgur.com/J761FTB.png )

**Comment by TeoTwawki** [comment] 2016-05-01 09:21
@R3P0FFXI NPC script needs total redo, gettin sick of seeing these issues for it

**Comment by TeoTwawki** [comment] 2016-05-01 09:38
@LegionDark/gm swap his item(s) for him, then close. We'll be working from the issue that is linked above this post after that.

**Comment by Samikana** [comment] 2016-05-01 13:19
@TeoTwawki I told Nekrol that I wouldn't be swapping out his items until all broken reforge issues are fixes in the script.  It would be unfair if I did it for Spectre.

**Comment by spectre99** [comment] 2016-05-01 18:28
It takes a lot of work to reforge gear.  I'm at a point where there isn't all that much I can do with my character.  I'm currently working on other reforge gear as well, both af1 and relic, and its very discouraging to know that its basically a game of Russian Roulette, spending weeks  towards something and then getting an incorrect item.  I appreciate all the work that you guys put into fixing things, and making the server going, however the point is to keep people playing and engaged right?  I've talked to a few other people about this since it happened to me, and now they don't even want to reforge since they'll be stuck with an incorrect item.  I looked at the other thread and it looks like the 'fix' is going to be a while.  I know the fix is probably going to take some time, but its pretty discouraging to see that the item could be traded pretty easily but isn't being done so. I'm not asking for any special treatment here but everyone who has worked towards a reforge has spent A LOT of time into getting these items.  The people who have gone to the trouble of doing the leg work should at least have their items exchanged.  I mean that IS why there are GMS in game right? To help the players, to make them WANT to play and spend more time on the server?  I'm currently in the process of collecting Forgotten items from dyna, as well as farming more apants, but now I don't even know if I should bother, since I have no idea which item will work or not, and even putting in a report won't do anything, and I'll more or less be stuck with an incorrect item after having spent weeks working towards something.

**Comment by Samikana** [comment] 2016-05-01 18:35
You can save the pity party of "I put a lot of work into this, I'm at endgame, I deserve this".  We get it.  I'm fully aware that you're deserving of your item and you put time into it, and so have others.  All of the staff put a lot of effort into something and it's unfortunate that the code was scripted poorly by somebody who doesn't code anymore, but you've already been told that, first of all, the issue is going to be taken care of. And second of all, that we're fixing the script.  I've actually even offered to Teo to fix the items myself.  The GMs are not in there to cater to your every single need, the GMs are there to fix variables and make sure people aren't breaking the rules.  And if you haven't realized, I haven't been in-game to deal with ANYTHING because I'm preparing for a surgery as well as juggling finals and state testing and two jobs.  If you want to bitch that "putting in a report won't fix anything", seriously just screw off, because not only were you told that the issue is going to be tended to, but you should look at just how many of your reports have been closed because they've been fixed.  

You were told you were going to get the correct item, if it happens tomorrow or in a week, why the fuck are you bitching?  This is a FREE server and if you hadn't realized, two people are managing it full time with only two other helpers.  It's impossible to tend to every single little issue and let me tell you that it's true when I say that your issue is the LEAST of my problems.

MAYBE Teo will log in and fix your item.  I'm not going to if you're going to give me a long, pity party paragraph because you have to wait a few days for a fix to be put in place.  Clearly it was going to happen before Tuesday, because that's when my surgery is.  Getting sick of the crying.

**Comment by spectre99** [comment] 2016-05-01 18:52
Uh... First of all, I'm not psychic, nowhere does it say that this solution is going to be fixed soon. I looked at the other thread that was referenced and the status was 'on hold - could take a while'. What I did see is Teo saying to switch the items out, which made me believe that it was a rather simple thing to do, and then someone else saying they weren't going to do it.  As a user I have VERY little information as to what is going on behind the scenes, then essentially being made to look like I'm a whiny bitch.

Look at it this way.  Recently you guys opened up a Q&A section, basically where the users can ask questions and give feedback since there was a consensus in the community that the staff wasn't exactly approachable and GMs didn't like taking questions without getting pissed about stuff.  As a user I can tell you THIS is exactly why people feel that way.  In my post I was in no way insulting or condescending to ANYONE.  I gave criticism in what I thought was a reasonable and adult manner.  People are afraid to give any kind of feedback that isn't positive because of this vary kind of reaction, and as a result you guys don't get the full picture because people are too afraid to say anything.  Of course from the looks of it it seems that even THIS post will be met with more criticism and claims that I'm crying/bitching.

**Comment by Samikana** [comment] 2016-05-01 18:58
No, you're being whiny because it's not happening as soon as you'd like
it.

We know we're understaffed.  But that thread is there for that exact
reason, meaning you don't need to give your "adult" opinion on Github while
I'm trying to communicate with Teo, NOT you, on what action to take.

Quite frankly, usually I'm fine with people asking questions.  But I'm
getting sick of players acting like they're entitled to something because
they put the work into a game.  We're putting in work behind the scenes and
then we get players who are still not satisfied because we can't fix
exactly what they want in a timely fashion.  There are more players than
just you that want things fixed.

The issue will get taken care of, and you were already told that and are
perfect ably capable of reasoning and deducting otherwise as well.

This is not the place to state your opinion, so don't treat it like it.

**Comment by atom0s** [comment] 2016-05-01 19:03
No offence spectre99 but your other response to this ticket did in fact come off as you crying/bitching. 

This server was started with 4? different coders with varying levels of coding skill. Two of those more major coders that were part of making a lot of what this server has are gone. A lot of their code was done poorly or rushed / copy-pasted that has grown to show issues as people find them. As it stands now there is one person doing 99% of the coding. And in that regard, that person is not even making new content, he is instead fixing all the mistakes of the past developers. This is been the current cycle of the server for a while now, so it is nothing new or nothing unknown to the playerbase. 

Coming here and giving some long story about how you basically feel ripped off or things are not being handled is a total shit show on your behalf. If you look at the news posts for all the recent maintenance's over the last several months they have all been fixes to content written by people that are no longer here. The staff is focused on getting the server stable and in doing so some content related things are being put aside to ensure that massive bits of the server are working properly. 

Just because you found a bug in an item trade/upgrade does not mean it is the end of the world or that you are being overlooked. Instead of coming here complaining, making a ticket with sufficient information on the problem is more than enough for the GMs to look into it. Compensation will be handled when the GM(s) can get to it. Just because they are not catering to your every need does not mean you are being overlooked or ignored. 

You have little understanding of how programming works it seems let alone the amount of stress and endless unpaid hours Teo is putting into this server to keep it going. As it stands, he is the only coder left working on things and he has not had a single moment to stop and work on anything new that he wants to do for the server. He has been, for the last several months, doing nothing but following behind the other coders that have left and fixing all their bugs and poorly written scripts. 

Rather than complain about your one single item making Teo hate himself and this server even more, perhaps have some patience and let the staff handle things when they can.

As it stands now, this ticket is filling up with garbage. I am locking it to staff-only responses.

**Comment by TeoTwawki** [comment] 2016-05-01 19:41
I don't have words. just head on desk for now.

**Comment by R3P0FFXI** [comment] 2016-05-17 18:08
@spectre99 this issue will be resolved in the forthcoming update

**Comment by R3P0FFXI** [comment] 2016-09-17 22:41
@spectre99 Issue resolved in Massive Update part 2 which went live today

**Closed by R3P0FFXI** 2016-09-17 22:41 UTC
Labels: ZFG. Go away. (you have irritated the staff), ¯\_(ツ)_/¯
