### ISSUE TITLE
Abyssea - Misareaux | Gukumatz freezes clients

### ISSUE THREAD

**Issue by lwrand** [LegionDark/Issues#1002] opened 2016-07-02 10:25 UTC
**Date & Time**: 02/07/2016 12:05 CEST (UTC+2)

**FFXI Client Version (use `/ver`)**: 30160427_0

**Character Name**: Croexi

**Nation**: Bastok

**Job(level)/Sub Job(level)**: BLU(99)/DNC(49)

**NPC or Monster or item Name**: Gukumatz (peiste type mob).

**Zone name & Coordinates (use `@where`)**: Abyssea - Misareaux | X:432 Y:15 Z:-392 (198)

**ffxiah.com link (for items issues only)**: 

**Multi-boxing? (multiple clients on same connection)**: Yes, 3 clients (Ashita).

**Steps To Reproduce / any other info**: Gukumatz crashed all 3 clients (Ashita), at the same time, plus another friend client (Windower) - We were 4 characters in total. Basically at some point, everything freezes and we had to close the clients. Speaking in LS, it seems to be related with the BLU spell "Sudden Lunge" which, if you keep spamming, it may lead to this strange behaviour. 
If you need further info and/or details - Let me know :).

Thanks,
/Croexi.

**Comment by TeoTwawki** [comment] 2016-07-02 16:23
If that's the case it should be reproducible on any mob by spamming sudden lunge.

**Comment by TeoTwawki** [comment] 2016-07-02 16:25
Please let me know if this can be tripped by sudden lunge on a non abyssea mob.

**Comment by lwrand** [comment] 2016-07-02 22:20
Hi Teo, 
 I don't think it's strictly connected to the "Sudden Lunge" frequency but more to the specific monster type: "Peiste". I'm saying so, since I had a similar issue with Kukulkan, In Abyssea - Konschtat (again a peiste type mob).

Let me know if I can help in any way (testing, etc...)

Thanks,
/Croexi.

**Comment by lwrand** [comment] 2016-07-03 11:47
Brief update: just killed Gukumatz without hitting "Sudden Lunge" a single time.
Hope it helps :)

**Comment by TeoTwawki** [comment] 2016-07-03 22:27
> Please let me know if this can be tripped by sudden lunge on a non abyssea and non voidwatch mob.

Is the info I need. If you can't do that its fine, I'll get around to it or someone will for me eventually, I don't expect you to drop everything and do debugging work :)

Sudden lunge previously has an issue which I was certain I'd fixed. You not crashing by not using it doesn't rule it out, it just tells me it _might not_ be it, and it could also be that whatever the cause _actually_ was didn't happen (say a particular monster attack, or the timing of a monster attack being stopped by the stun status, or a million other little things). But if we can trip the crash solely on sudden lung, _then_ it would tell me 100% its definitely sudden lunge or blue based stuns again (it was pretty much every blu stun in existence last time..).

**Comment by TeoTwawki** [comment] 2016-08-31 21:12
Whatever the issue really is, its seems likely to be common to other Peiste type mobs as well.

**Comment by R3P0FFXI** [comment] 2016-11-16 20:40
@lwrand Can you please verify if this is still happening this mob should have been fixed in last night maint.

**Comment by TeoTwawki** [comment] 2016-11-17 00:40
Please ignore that last request.

> (3:41:27 PM) R3P0FFXI: should we disable sudden lunge for now?
(3:41:34 PM) R3P0FFXI: see if ppl stop crashing?
(3:41:37 PM) Teo: no
(3:41:43 PM) R3P0FFXI: we have like 4 tickets on that issue
(3:41:52 PM) Teo: its not a problem with sudden lunge itself
(3:42:02 PM) Teo: I'm kind of tired of explkaining it over and over
(3:42:49 PM) R3P0FFXI: lol its just me asking as ive not really paid attention to whats going on with it
(3:45:37 PM) Teo: if I take away sudden lunge the process repeats with headbutt
(3:45:49 PM) Teo: "should we disable head butt for now?"
(3:46:01 PM) Teo: this will go on till we run out of stuns

**Comment by TeoTwawki** [comment] 2016-11-17 00:46
see also:
#1115
#1176
https://github.com/DarkstarProject/darkstar/issues/3393

**Closed by TeoTwawki** 2016-11-17 00:46 UTC
